# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .address import Address
    from .api_key_exchange_response import ApiKeyExchangeResponse
    from .bulk_batch_list_response import BulkBatchListResponse
    from .bulk_batch_response import BulkBatchResponse
    from .bulk_batch_status import BulkBatchStatus
    from .bulk_row_result import BulkRowResult
    from .bulk_row_validation import BulkRowValidation
    from .bulk_upload_request import BulkUploadRequest
    from .bulk_validate_response import BulkValidateResponse
    from .checkout_session_response import CheckoutSessionResponse
    from .components import Components
    from .components_db import ComponentsDb
    from .components_ordering import ComponentsOrdering
    from .components_queue import ComponentsQueue
    from .coverage_info import CoverageInfo
    from .coverage_platform import CoveragePlatform
    from .customer_notification_status import CustomerNotificationStatus
    from .customer_notifications import CustomerNotifications
    from .delivery_map_point import DeliveryMapPoint
    from .delivery_map_response import DeliveryMapResponse
    from .device_approve_response import DeviceApproveResponse
    from .device_code_create import DeviceCodeCreate
    from .device_code_info import DeviceCodeInfo
    from .device_code_response import DeviceCodeResponse
    from .error_code import ErrorCode
    from .error_detail import ErrorDetail
    from .error_details import ErrorDetails
    from .error_response import ErrorResponse
    from .field_error import FieldError
    from .fulfillment_concession import FulfillmentConcession
    from .fulfillment_concession_concern import FulfillmentConcessionConcern
    from .fulfillment_mode import FulfillmentMode
    from .fulfillment_preferences import FulfillmentPreferences
    from .http_validation_error import HttpValidationError
    from .lifetime_stats_response import LifetimeStatsResponse
    from .lifetime_totals import LifetimeTotals
    from .lifetime_v1stats import LifetimeV1Stats
    from .lifetime_v1stats_source import LifetimeV1StatsSource
    from .margin_spec import MarginSpec
    from .margin_spec_type import MarginSpecType
    from .order_cart_item import OrderCartItem
    from .order_connect_info import OrderConnectInfo
    from .order_create import OrderCreate
    from .order_fulfillment import OrderFulfillment
    from .order_item_response import OrderItemResponse
    from .order_item_status import OrderItemStatus
    from .order_job_result import OrderJobResult
    from .order_list_response import OrderListResponse
    from .order_milestone import OrderMilestone
    from .order_milestone_type import OrderMilestoneType
    from .order_payment import OrderPayment
    from .order_payment_info import OrderPaymentInfo
    from .order_payment_info_mode import OrderPaymentInfoMode
    from .order_payment_mode import OrderPaymentMode
    from .order_price_components import OrderPriceComponents
    from .order_product import OrderProduct
    from .order_response import OrderResponse
    from .order_status import OrderStatus
    from .order_timeline_response import OrderTimelineResponse
    from .payment_quote import PaymentQuote
    from .payment_required_error_body import PaymentRequiredErrorBody
    from .pending_payment_client import PendingPaymentClient
    from .pending_payment_product import PendingPaymentProduct
    from .pending_payment_response import PendingPaymentResponse
    from .pending_payment_response_status import PendingPaymentResponseStatus
    from .product_condition import ProductCondition
    from .product_search_response import ProductSearchResponse
    from .product_search_result import ProductSearchResult
    from .product_variant import ProductVariant
    from .public_health_response import PublicHealthResponse
    from .public_health_response_status import PublicHealthResponseStatus
    from .public_retailer import PublicRetailer
    from .public_retailer_list_response import PublicRetailerListResponse
    from .public_tracking_destination import PublicTrackingDestination
    from .public_tracking_item import PublicTrackingItem
    from .public_tracking_response import PublicTrackingResponse
    from .public_tracking_shipment import PublicTrackingShipment
    from .recent_call import RecentCall
    from .retailer_check_checkout import RetailerCheckCheckout
    from .retailer_check_evidence import RetailerCheckEvidence
    from .retailer_check_response import RetailerCheckResponse
    from .retailer_check_retailer import RetailerCheckRetailer
    from .retailer_credentials_list_response import RetailerCredentialsListResponse
    from .retailer_credentials_response import RetailerCredentialsResponse
    from .return_request_item import ReturnRequestItem
    from .return_request_list_response import ReturnRequestListResponse
    from .return_request_reason import ReturnRequestReason
    from .return_request_response import ReturnRequestResponse
    from .return_request_status import ReturnRequestStatus
    from .return_request_summary import ReturnRequestSummary
    from .sandbox_claim_response import SandboxClaimResponse
    from .sandbox_claim_summary import SandboxClaimSummary
    from .sandbox_key_create import SandboxKeyCreate
    from .sandbox_key_response import SandboxKeyResponse
    from .sandbox_status_response import SandboxStatusResponse
    from .search_response import SearchResponse
    from .sku import Sku
    from .starter_credit import StarterCredit
    from .starter_pick import StarterPick
    from .tracking_checkpoint_response import TrackingCheckpointResponse
    from .tracking_number_response import TrackingNumberResponse
    from .tracking_status import TrackingStatus
    from .usage_metric import UsageMetric
    from .user_usage_response import UserUsageResponse
    from .validation_error import ValidationError
    from .validation_error_loc_item import ValidationErrorLocItem
    from .wallet_response import WalletResponse
    from .wallet_type import WalletType
    from .webhook_endpoint_response import WebhookEndpointResponse
_dynamic_imports: typing.Dict[str, str] = {
    "Address": ".address",
    "ApiKeyExchangeResponse": ".api_key_exchange_response",
    "BulkBatchListResponse": ".bulk_batch_list_response",
    "BulkBatchResponse": ".bulk_batch_response",
    "BulkBatchStatus": ".bulk_batch_status",
    "BulkRowResult": ".bulk_row_result",
    "BulkRowValidation": ".bulk_row_validation",
    "BulkUploadRequest": ".bulk_upload_request",
    "BulkValidateResponse": ".bulk_validate_response",
    "CheckoutSessionResponse": ".checkout_session_response",
    "Components": ".components",
    "ComponentsDb": ".components_db",
    "ComponentsOrdering": ".components_ordering",
    "ComponentsQueue": ".components_queue",
    "CoverageInfo": ".coverage_info",
    "CoveragePlatform": ".coverage_platform",
    "CustomerNotificationStatus": ".customer_notification_status",
    "CustomerNotifications": ".customer_notifications",
    "DeliveryMapPoint": ".delivery_map_point",
    "DeliveryMapResponse": ".delivery_map_response",
    "DeviceApproveResponse": ".device_approve_response",
    "DeviceCodeCreate": ".device_code_create",
    "DeviceCodeInfo": ".device_code_info",
    "DeviceCodeResponse": ".device_code_response",
    "ErrorCode": ".error_code",
    "ErrorDetail": ".error_detail",
    "ErrorDetails": ".error_details",
    "ErrorResponse": ".error_response",
    "FieldError": ".field_error",
    "FulfillmentConcession": ".fulfillment_concession",
    "FulfillmentConcessionConcern": ".fulfillment_concession_concern",
    "FulfillmentMode": ".fulfillment_mode",
    "FulfillmentPreferences": ".fulfillment_preferences",
    "HttpValidationError": ".http_validation_error",
    "LifetimeStatsResponse": ".lifetime_stats_response",
    "LifetimeTotals": ".lifetime_totals",
    "LifetimeV1Stats": ".lifetime_v1stats",
    "LifetimeV1StatsSource": ".lifetime_v1stats_source",
    "MarginSpec": ".margin_spec",
    "MarginSpecType": ".margin_spec_type",
    "OrderCartItem": ".order_cart_item",
    "OrderConnectInfo": ".order_connect_info",
    "OrderCreate": ".order_create",
    "OrderFulfillment": ".order_fulfillment",
    "OrderItemResponse": ".order_item_response",
    "OrderItemStatus": ".order_item_status",
    "OrderJobResult": ".order_job_result",
    "OrderListResponse": ".order_list_response",
    "OrderMilestone": ".order_milestone",
    "OrderMilestoneType": ".order_milestone_type",
    "OrderPayment": ".order_payment",
    "OrderPaymentInfo": ".order_payment_info",
    "OrderPaymentInfoMode": ".order_payment_info_mode",
    "OrderPaymentMode": ".order_payment_mode",
    "OrderPriceComponents": ".order_price_components",
    "OrderProduct": ".order_product",
    "OrderResponse": ".order_response",
    "OrderStatus": ".order_status",
    "OrderTimelineResponse": ".order_timeline_response",
    "PaymentQuote": ".payment_quote",
    "PaymentRequiredErrorBody": ".payment_required_error_body",
    "PendingPaymentClient": ".pending_payment_client",
    "PendingPaymentProduct": ".pending_payment_product",
    "PendingPaymentResponse": ".pending_payment_response",
    "PendingPaymentResponseStatus": ".pending_payment_response_status",
    "ProductCondition": ".product_condition",
    "ProductSearchResponse": ".product_search_response",
    "ProductSearchResult": ".product_search_result",
    "ProductVariant": ".product_variant",
    "PublicHealthResponse": ".public_health_response",
    "PublicHealthResponseStatus": ".public_health_response_status",
    "PublicRetailer": ".public_retailer",
    "PublicRetailerListResponse": ".public_retailer_list_response",
    "PublicTrackingDestination": ".public_tracking_destination",
    "PublicTrackingItem": ".public_tracking_item",
    "PublicTrackingResponse": ".public_tracking_response",
    "PublicTrackingShipment": ".public_tracking_shipment",
    "RecentCall": ".recent_call",
    "RetailerCheckCheckout": ".retailer_check_checkout",
    "RetailerCheckEvidence": ".retailer_check_evidence",
    "RetailerCheckResponse": ".retailer_check_response",
    "RetailerCheckRetailer": ".retailer_check_retailer",
    "RetailerCredentialsListResponse": ".retailer_credentials_list_response",
    "RetailerCredentialsResponse": ".retailer_credentials_response",
    "ReturnRequestItem": ".return_request_item",
    "ReturnRequestListResponse": ".return_request_list_response",
    "ReturnRequestReason": ".return_request_reason",
    "ReturnRequestResponse": ".return_request_response",
    "ReturnRequestStatus": ".return_request_status",
    "ReturnRequestSummary": ".return_request_summary",
    "SandboxClaimResponse": ".sandbox_claim_response",
    "SandboxClaimSummary": ".sandbox_claim_summary",
    "SandboxKeyCreate": ".sandbox_key_create",
    "SandboxKeyResponse": ".sandbox_key_response",
    "SandboxStatusResponse": ".sandbox_status_response",
    "SearchResponse": ".search_response",
    "Sku": ".sku",
    "StarterCredit": ".starter_credit",
    "StarterPick": ".starter_pick",
    "TrackingCheckpointResponse": ".tracking_checkpoint_response",
    "TrackingNumberResponse": ".tracking_number_response",
    "TrackingStatus": ".tracking_status",
    "UsageMetric": ".usage_metric",
    "UserUsageResponse": ".user_usage_response",
    "ValidationError": ".validation_error",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "WalletResponse": ".wallet_response",
    "WalletType": ".wallet_type",
    "WebhookEndpointResponse": ".webhook_endpoint_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Address",
    "ApiKeyExchangeResponse",
    "BulkBatchListResponse",
    "BulkBatchResponse",
    "BulkBatchStatus",
    "BulkRowResult",
    "BulkRowValidation",
    "BulkUploadRequest",
    "BulkValidateResponse",
    "CheckoutSessionResponse",
    "Components",
    "ComponentsDb",
    "ComponentsOrdering",
    "ComponentsQueue",
    "CoverageInfo",
    "CoveragePlatform",
    "CustomerNotificationStatus",
    "CustomerNotifications",
    "DeliveryMapPoint",
    "DeliveryMapResponse",
    "DeviceApproveResponse",
    "DeviceCodeCreate",
    "DeviceCodeInfo",
    "DeviceCodeResponse",
    "ErrorCode",
    "ErrorDetail",
    "ErrorDetails",
    "ErrorResponse",
    "FieldError",
    "FulfillmentConcession",
    "FulfillmentConcessionConcern",
    "FulfillmentMode",
    "FulfillmentPreferences",
    "HttpValidationError",
    "LifetimeStatsResponse",
    "LifetimeTotals",
    "LifetimeV1Stats",
    "LifetimeV1StatsSource",
    "MarginSpec",
    "MarginSpecType",
    "OrderCartItem",
    "OrderConnectInfo",
    "OrderCreate",
    "OrderFulfillment",
    "OrderItemResponse",
    "OrderItemStatus",
    "OrderJobResult",
    "OrderListResponse",
    "OrderMilestone",
    "OrderMilestoneType",
    "OrderPayment",
    "OrderPaymentInfo",
    "OrderPaymentInfoMode",
    "OrderPaymentMode",
    "OrderPriceComponents",
    "OrderProduct",
    "OrderResponse",
    "OrderStatus",
    "OrderTimelineResponse",
    "PaymentQuote",
    "PaymentRequiredErrorBody",
    "PendingPaymentClient",
    "PendingPaymentProduct",
    "PendingPaymentResponse",
    "PendingPaymentResponseStatus",
    "ProductCondition",
    "ProductSearchResponse",
    "ProductSearchResult",
    "ProductVariant",
    "PublicHealthResponse",
    "PublicHealthResponseStatus",
    "PublicRetailer",
    "PublicRetailerListResponse",
    "PublicTrackingDestination",
    "PublicTrackingItem",
    "PublicTrackingResponse",
    "PublicTrackingShipment",
    "RecentCall",
    "RetailerCheckCheckout",
    "RetailerCheckEvidence",
    "RetailerCheckResponse",
    "RetailerCheckRetailer",
    "RetailerCredentialsListResponse",
    "RetailerCredentialsResponse",
    "ReturnRequestItem",
    "ReturnRequestListResponse",
    "ReturnRequestReason",
    "ReturnRequestResponse",
    "ReturnRequestStatus",
    "ReturnRequestSummary",
    "SandboxClaimResponse",
    "SandboxClaimSummary",
    "SandboxKeyCreate",
    "SandboxKeyResponse",
    "SandboxStatusResponse",
    "SearchResponse",
    "Sku",
    "StarterCredit",
    "StarterPick",
    "TrackingCheckpointResponse",
    "TrackingNumberResponse",
    "TrackingStatus",
    "UsageMetric",
    "UserUsageResponse",
    "ValidationError",
    "ValidationErrorLocItem",
    "WalletResponse",
    "WalletType",
    "WebhookEndpointResponse",
]
