# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sandbox_claim_summary import SandboxClaimSummary
from .starter_credit import StarterCredit


class ApiKeyExchangeResponse(UniversalBaseModel):
    """
    The issued key, plus what the agent needs to act on it right away.
    """

    id: str
    key: str
    name: typing.Optional[str] = None
    is_active: bool
    is_test: bool
    created_at: dt.datetime
    wallet_balance_cents: int = pydantic.Field()
    """
    Spendable wallet balance of the account the key belongs to.
    """

    sandbox: typing.Optional[SandboxClaimSummary] = pydantic.Field(default=None)
    """
    What the sandbox claim moved, when `sandbox_key` was sent.
    """

    starter_credit: typing.Optional[StarterCredit] = pydantic.Field(default=None)
    """
    Wallet credit granted alongside this key, if the account earned one, with a few items it is known to cover.
    """

    api_key: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
