# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DeliveryMapPoint(UniversalBaseModel):
    """
    One delivered-order marker for the marketing site's globe.

    Coordinates are a ZIP centroid rounded to two decimals — never a street
    address, but the rounding does not hide which ZIP (see
    ``lib.routers.stats``). Deliberately carries no order id, name, address,
    or per-point timestamp.
    """

    lat: float
    long_: typing_extensions.Annotated[float, FieldMetadata(alias="long"), pydantic.Field(alias="long")]
    emoji: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
