# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeviceCodeInfo(UniversalBaseModel):
    """
    What the approval page shows before the human decides. Public: it holds
    only what the agent chose to say about itself.
    """

    user_code: str
    name: str
    source: str = pydantic.Field()
    """
    Runtime guessed from the requesting User-Agent (claude-code, codex, curl, …).
    """

    sandbox_attached: bool = pydantic.Field()
    """
    Approval will also claim the agent's sandbox into the approving account.
    """

    starter_credit_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    Wallet credit approval would add, when the attached sandbox has placed an order and the account has not had one; null otherwise.
    """

    status: str = pydantic.Field()
    """
    pending | approved | denied
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
