# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FieldError(UniversalBaseModel):
    """
    A single field-level validation failure from a worker.

    Mirrors Sonic's `FieldError` (src/agent/types.py): when a job fails schema
    validation the worker reports one of these per offending field, so consumers
    can show "state should be 'NY', got 'New York'" instead of a bare count.
    """

    field: str
    code: str
    message: typing.Optional[str] = None
    received: typing.Optional[typing.Any] = None
    expected: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
