# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fulfillment_concession_concern import FulfillmentConcessionConcern


class FulfillmentConcession(UniversalBaseModel):
    """
    One rule that was actually relaxed while placing the order.
    """

    concern: FulfillmentConcessionConcern
    code: str = pydantic.Field()
    """
    Worker error code that would have failed a strict order.
    """

    message: typing.Optional[str] = None
    item_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Order item this concession is about, if any.
    """

    url: typing.Optional[str] = None
    requested_quantity: typing.Optional[int] = None
    fulfilled_quantity: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
