# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .margin_spec_type import MarginSpecType


class MarginSpec(UniversalBaseModel):
    """
    Customer's markup on the order cost (computed before fees).
    """

    type: MarginSpecType
    value: float = pydantic.Field()
    """
    Cents when type='flat'; a percentage when type='percent' (e.g. 15 == 15%).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
