# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OrderConnectInfo(UniversalBaseModel):
    """
    Stripe Connect charge + state for an order paid via Connect. Present only
    when the order has a Connect profile; ``null`` for prepaid-wallet orders. All
    amounts in cents.

    ``state`` moves ``secured`` → ``captured`` (or ``released``/``refunded`` on a
    terminal outcome). The post-capture fields (``order_cost`` and below) are
    populated once Zinc places the order with the retailer and the actual total
    is captured.
    """

    state: str = pydantic.Field()
    """
    secured | captured | released | refunded | …
    """

    secured_amount: typing.Optional[int] = None
    order_cost: typing.Optional[int] = pydantic.Field(default=None)
    """
    Actual order cost (goods) captured when the order is placed.
    """

    customer_margin: typing.Optional[int] = None
    zinc_fee: typing.Optional[int] = None
    stripe_fee: typing.Optional[int] = None
    final_charge: typing.Optional[int] = None
    transfer_amount: typing.Optional[int] = None
    payment_intent_id: typing.Optional[str] = None
    connected_account_id: typing.Optional[str] = None
    simulated: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
