# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_cart_item import OrderCartItem


class OrderPriceComponents(UniversalBaseModel):
    """
    Retailer price breakdown for an order, all amounts in cents.

    Lenient by design — every field is optional and unknown keys are preserved
    (``extra="allow"``) — because it mirrors fulfillment output that may be
    partial (e.g. a failed order) or carry extra detail. Documents the common
    fields without revalidating the raw payload.
    """

    subtotal: typing.Optional[int] = None
    tax: typing.Optional[int] = None
    shipping: typing.Optional[int] = None
    discount: typing.Optional[int] = pydantic.Field(default=None)
    """
    Promotion/free-shipping discount applied by the retailer, as a positive magnitude subtracted from the total. A nonzero `shipping` paired with an equal `discount` means shipping was itemized but waived — the total correctly excludes it.
    """

    fees: typing.Optional[int] = pydantic.Field(default=None)
    """
    Retailer fees not folded into subtotal/shipping/tax (gift wrap, import/regulatory charges), as a positive magnitude added to the total. Surfaced so a total exceeding the shown parts reads as an itemized fee rather than an unexplained charge.
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Order total in `currency` (subtotal + tax + shipping + fees − discount).
    """

    converted_payment_total: typing.Optional[int] = pydantic.Field(default=None)
    """
    `total` converted to the currency actually charged.
    """

    currency: typing.Optional[str] = None
    payment_currency: typing.Optional[str] = None
    cart_items: typing.Optional[typing.List[OrderCartItem]] = pydantic.Field(default=None)
    """
    Per-product rows making up `subtotal`. Distinct from `line_items`, which carries order-level adjustments (discounts, fees) and shares no fields with these — a discount is never a cart row. Null when the retailer's checkout page did not expose readable line items, so handle both `null` and `[]`. Individual fields may also be null on a row we could only partly read. Best-effort: `sum(line_total)` normally equals `subtotal`, but that is not guaranteed and must not be used as a billing input — the charge is always driven by `total`.
    """

    line_items: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Order-level adjustments, each `{description, amount, category}`. Null — not `[]` — when the producer didn't supply them, which is every BizAPI-placed order today, so null-check before iterating.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
