# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .product_condition import ProductCondition
from .product_variant import ProductVariant


class OrderProduct(UniversalBaseModel):
    """
    Product item for an order.

    For example:
    ````{
        url: "https://www.amazon.com/dp/B07JGBW826",
        quantity: 1
    }```
    """

    url: str
    quantity: typing.Optional[int] = None
    variant: typing.Optional[typing.List[ProductVariant]] = pydantic.Field(default=None)
    """
    Product variants to select (e.g., color, size)
    """

    condition_in: typing.Optional[typing.List[ProductCondition]] = pydantic.Field(default=None)
    """
    Condition allowlist. The agent only buys an offer whose condition is in this list. Each value must be a canonical condition. Omit or send null/[] for no constraint.
    """

    condition_not_in: typing.Optional[typing.List[ProductCondition]] = pydantic.Field(default=None)
    """
    Condition denylist. The agent will not buy an offer whose condition is in this list. Each value must be a canonical condition. Omit or send null/[] for no constraint.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
