# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fulfillment_concession import FulfillmentConcession
from .fulfillment_mode import FulfillmentMode


class OrderFulfillment(UniversalBaseModel):
    """
    What was asked (the per-concern modes, all null on a strict order) plus
    what was actually relaxed (``concessions``, empty when the order was
    fulfilled exactly as requested — which is every strict order).
    """

    gift: typing.Optional[FulfillmentMode] = pydantic.Field(default=None)
    """
    `best_effort`: if the retailer offers no free gift option, place a normal order instead of failing with `gift_option_unavailable`. Requires `is_gift: true`. Omit to keep the gift requirement strict.
    """

    items: typing.Optional[FulfillmentMode] = pydantic.Field(default=None)
    """
    `best_effort`: if an item can't be bought (not found, out of stock, variant or condition unavailable, add-to-cart failed), skip it and ship the rest — its status becomes `skipped`. An empty cart still fails. Omit for all-or-nothing.
    """

    quantity: typing.Optional[FulfillmentMode] = pydantic.Field(default=None)
    """
    `best_effort`: if the retailer caps an item below the requested quantity, buy the cap instead of failing with `quantity_limit_exceeded`. Omit to require the full quantity.
    """

    concessions: typing.Optional[typing.List[FulfillmentConcession]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
