# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PaymentQuote(UniversalBaseModel):
    """
    What the hold covers. All amounts in cents.
    """

    max_price_cents: int = pydantic.Field()
    """
    The order's spending cap.
    """

    order_fee_cents: int = pydantic.Field()
    """
    Zinc's per-order fee.
    """

    stripe_fee_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    Stripe's processing cut, grossed into hold_cents so the order fee is what Zinc actually nets.
    """

    hold_cents: int = pydantic.Field()
    """
    Authorized on the card: max_price + fee + processing. Only the actual retailer total plus those is captured; the rest is released.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
