# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PendingPaymentClient(UniversalBaseModel):
    """
    The assistant the buyer came from, so the payment page can send them
    back once the order is placed.
    """

    name: str = pydantic.Field()
    """
    Display name, e.g. 'Claude'.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Where 'back' goes when the tab cannot close itself; null when the client has no web home we know of.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
