# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProductVariant(UniversalBaseModel):
    """
    Product variant schema for selecting product options (color, size, etc.).
    """

    label: str = pydantic.Field()
    """
    Variant label (e.g., 'Color', 'Size')
    """

    value: str = pydantic.Field()
    """
    Variant value (e.g., 'Black', 'Large')
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
