# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PublicRetailer(UniversalBaseModel):
    """
    A supported retailer in the public catalog — one flat object per brand.

    This is the customer-facing "what do you support?" shape: a retailer
    identifier, where to buy from, the countries we ship to, the free-shipping
    policy, and how orders are fulfilled (Zinc-managed vs. bring-your-own
    account). Internal guest-checkout/credential details remain omitted.
    """

    retailer: str = pydantic.Field()
    """
    Stable retailer identifier / slug, e.g. 'amazon'.
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-friendly name, e.g. 'Amazon'.
    """

    base_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Retailer domain, e.g. 'amazon.com'.
    """

    no_account_needed: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether Zinc can place the order for you without your own account (guest checkout or Zinc-managed credentials).
    """

    use_your_account: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether you can order through your own retailer account.
    """

    supported_countries: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    ISO 3166-1 alpha-2 countries we ship to (defaults to ['US']).
    """

    free_shipping: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether free shipping is offered (unconditionally or above free_shipping_threshold_cents).
    """

    free_shipping_threshold_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    Order subtotal (cents) at/above which shipping is free; null means no threshold.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
