# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RetailerCheckCheckout(UniversalBaseModel):
    """
    How a customer can pay at this store.
    """

    guest_checkout: bool = pydantic.Field()
    """
    Zinc can check out without a customer account — the store allows guests, or Zinc holds a shared account for it. When false, an order here must carry `retailer_credentials_id`.
    """

    use_your_account: bool = pydantic.Field()
    """
    The customer can supply their own retailer login.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
