# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .return_request_item import ReturnRequestItem
from .return_request_reason import ReturnRequestReason
from .return_request_status import ReturnRequestStatus


class ReturnRequestSummary(UniversalBaseModel):
    id: str
    status: ReturnRequestStatus
    reason: ReturnRequestReason
    notes: typing.Optional[str] = None
    resolution_notes: typing.Optional[str] = None
    items: typing.Optional[typing.List[ReturnRequestItem]] = None
    label_urls: typing.Optional[typing.List[str]] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
