# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SandboxStatusResponse(UniversalBaseModel):
    """
    Whether this sandbox has been claimed yet.

    Lets an agent learn the outcome of a claim it can't see — the thing a
    device-code grant would give it for free (see issue #825).
    """

    claimed: bool = pydantic.Field()
    """
    True once a human has folded this sandbox into an account — at which point this key is a real account's key and keeps working.
    """

    claimed_by_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    The claiming account's email, once claimed.
    """

    hint: str = pydantic.Field()
    """
    What to do next given this status.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
