# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Sku(UniversalBaseModel):
    """
    A cross-retailer buyable listing. Pass `url` to /orders to buy it.
    """

    url: str
    retailer: str
    title: typing.Optional[str] = None
    image: typing.Optional[str] = None
    brand: typing.Optional[str] = None
    price: typing.Optional[int] = None
    stars: typing.Optional[float] = None
    num_reviews: typing.Optional[int] = None
    available: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
