# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .starter_pick import StarterPick


class StarterCredit(UniversalBaseModel):
    """
    The wallet this key spends from, in the terms an agent needs to place
    its first order. Always present on a key-issuing response, whether or not
    a starter credit landed this time: an agent must never have to infer its
    budget from a null.
    """

    cents: int = pydantic.Field()
    """
    Starter credit added to the wallet by this approval; 0 when none was.
    """

    reason: str = pydantic.Field()
    """
    `granted`; `already_granted` (the account received its one starter credit earlier); `no_sandbox_order` (no proven sandbox was attached).
    """

    wallet_balance_cents: int = pydantic.Field()
    """
    Spendable wallet balance right now.
    """

    max_price_cents: int = pydantic.Field()
    """
    Largest `max_price` an order can carry on the wallet alone (balance minus the per-order fee).
    """

    message: str = pydantic.Field()
    """
    Plain-language version of the above, for the operator.
    """

    picks: typing.List[StarterPick] = pydantic.Field()
    """
    Suggested first purchases (a bag of coffee).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
