# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tracking_checkpoint_response import TrackingCheckpointResponse
from .tracking_number_response_item_mapping import TrackingNumberResponseItemMapping
from .tracking_status import TrackingStatus


class TrackingNumberResponse(UniversalBaseModel):
    """
    Response model for tracking number data.

    ``status`` is the authoritative carrier-derived shipment state and is always
    present. ``checkpoints`` is the per-scan timeline; it's embedded on the
    single-order read (``GET /orders/{id}``) and, on the list endpoint, only
    when ``include=tracking_events`` is requested.
    """

    id: str
    carrier: str
    tracking_number: str
    zinc_tracking_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Zinc-issued tracking number under pseudo-carrier ZNLOGIC (format ZPY…YQ). Carrier-independent alias for this shipment; assigned once and never changes, even if the carrier tracking is corrected.
    """

    zinc_tracking_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public tracking URL for the Zinc tracking number (17track.net).
    """

    status: typing.Optional[TrackingStatus] = pydantic.Field(default=None)
    """
    Carrier-derived shipment state (pending, in_transit, delivered).
    """

    estimated_delivery_date: typing.Optional[dt.date] = pydantic.Field(default=None)
    """
    Carrier-reported delivery estimate for this shipment, as a destination-local calendar date. Refreshed on every carrier poll; null when the carrier hasn't reported one.
    """

    checkpoints: typing.Optional[typing.List[TrackingCheckpointResponse]] = pydantic.Field(default=None)
    """
    Carrier scan events, most recent first. Empty unless the checkpoint timeline was requested.
    """

    order_item_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Ids of the `items[]` this package carries, best effort. Null when unknown (never an empty list). Populated when the order has one item, or once a single-package order is delivered; see `item_mapping` for how much to trust it.
    """

    item_mapping: typing.Optional[TrackingNumberResponseItemMapping] = pydantic.Field(default=None)
    """
    Confidence of `order_item_ids`: `exact` means the package cannot carry anything else; `inferred` means at least one entry is a best-effort guess. Null when `order_item_ids` is null.
    """

    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
