# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .recent_call import RecentCall
from .usage_metric import UsageMetric


class UserUsageResponse(UniversalBaseModel):
    window_days: int
    since: str
    metrics: typing.Dict[str, UsageMetric]
    recent: typing.List[RecentCall]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
