# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.api_key_exchange_response import ApiKeyExchangeResponse
from ..types.device_approve_response import DeviceApproveResponse
from ..types.device_code_create import DeviceCodeCreate
from ..types.device_code_info import DeviceCodeInfo
from ..types.device_code_response import DeviceCodeResponse
from .raw_client import AsyncRawDeviceClient, RawDeviceClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DeviceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDeviceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDeviceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDeviceClient
        """
        return self._raw_client

    def create_device_code(
        self,
        *,
        authorization: typing.Optional[str] = None,
        request: typing.Optional[DeviceCodeCreate] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeviceCodeResponse:
        """
        Mint a device code. No account needed.

        Send your `zn_test_` sandbox key as the bearer and the sandbox comes along:
        when the owner approves, its orders and key move onto their account and
        your sandbox key keeps working, alongside the live key you receive.

        Parameters
        ----------
        authorization : typing.Optional[str]

        request : typing.Optional[DeviceCodeCreate]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceCodeResponse
            Successful Response

        Examples
        --------
        from zinc import DeviceCodeCreate, ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.device.create_device_code(
            request=DeviceCodeCreate(),
        )
        """
        _response = self._raw_client.create_device_code(
            authorization=authorization, request=request, request_options=request_options
        )
        return _response.data

    def describe_device_code(
        self, user_code: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeviceCodeInfo:
        """
        Public on purpose: it holds only what the agent said about itself, and
        the approval page needs it before the human has signed in.

        Parameters
        ----------
        user_code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceCodeInfo
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.device.describe_device_code(
            user_code="user_code",
        )
        """
        _response = self._raw_client.describe_device_code(user_code, request_options=request_options)
        return _response.data

    def decide_device_code(
        self,
        *,
        user_code: str,
        granted: bool,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeviceApproveResponse:
        """
        The human's decision. A machine credential must never make it: an API
        key approving a device code would be a key minting a key.

        Parameters
        ----------
        user_code : str

        granted : bool

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceApproveResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.device.decide_device_code(
            user_code="user_code",
            granted=True,
        )
        """
        _response = self._raw_client.decide_device_code(
            user_code=user_code, granted=granted, authorization=authorization, request_options=request_options
        )
        return _response.data

    def redeem_device_code(
        self, *, device_code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyExchangeResponse:
        """
        Parameters
        ----------
        device_code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyExchangeResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.device.redeem_device_code(
            device_code="device_code",
        )
        """
        _response = self._raw_client.redeem_device_code(device_code=device_code, request_options=request_options)
        return _response.data


class AsyncDeviceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDeviceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDeviceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDeviceClient
        """
        return self._raw_client

    async def create_device_code(
        self,
        *,
        authorization: typing.Optional[str] = None,
        request: typing.Optional[DeviceCodeCreate] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeviceCodeResponse:
        """
        Mint a device code. No account needed.

        Send your `zn_test_` sandbox key as the bearer and the sandbox comes along:
        when the owner approves, its orders and key move onto their account and
        your sandbox key keeps working, alongside the live key you receive.

        Parameters
        ----------
        authorization : typing.Optional[str]

        request : typing.Optional[DeviceCodeCreate]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceCodeResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient, DeviceCodeCreate

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.device.create_device_code(
                request=DeviceCodeCreate(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_device_code(
            authorization=authorization, request=request, request_options=request_options
        )
        return _response.data

    async def describe_device_code(
        self, user_code: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeviceCodeInfo:
        """
        Public on purpose: it holds only what the agent said about itself, and
        the approval page needs it before the human has signed in.

        Parameters
        ----------
        user_code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceCodeInfo
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.device.describe_device_code(
                user_code="user_code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.describe_device_code(user_code, request_options=request_options)
        return _response.data

    async def decide_device_code(
        self,
        *,
        user_code: str,
        granted: bool,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeviceApproveResponse:
        """
        The human's decision. A machine credential must never make it: an API
        key approving a device code would be a key minting a key.

        Parameters
        ----------
        user_code : str

        granted : bool

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeviceApproveResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.device.decide_device_code(
                user_code="user_code",
                granted=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.decide_device_code(
            user_code=user_code, granted=granted, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def redeem_device_code(
        self, *, device_code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ApiKeyExchangeResponse:
        """
        Parameters
        ----------
        device_code : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ApiKeyExchangeResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.device.redeem_device_code(
                device_code="device_code",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.redeem_device_code(device_code=device_code, request_options=request_options)
        return _response.data
