# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import ZincioApiEnvironment

if typing.TYPE_CHECKING:
    from .agent.client import AgentClient, AsyncAgentClient
    from .health.client import AsyncHealthClient, HealthClient
    from .managed_accounts.client import AsyncManagedAccountsClient, ManagedAccountsClient
    from .orders.client import AsyncOrdersClient, OrdersClient
    from .products.client import AsyncProductsClient, ProductsClient
    from .retailers.client import AsyncRetailersClient, RetailersClient
    from .returns.client import AsyncReturnsClient, ReturnsClient
    from .sandbox.client import AsyncSandboxClient, SandboxClient
    from .search.client import AsyncSearchClient, SearchClient
    from .tracking.client import AsyncTrackingClient, TrackingClient
    from .usage.client import AsyncUsageClient, UsageClient


class ZincioApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : ZincioApiEnvironment
        The environment to use for requests from the client. from .environment import ZincioApiEnvironment



        Defaults to ZincioApiEnvironment.PRODUCTION



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from zincio import ZincioApi

    client = ZincioApi(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: ZincioApiEnvironment = ZincioApiEnvironment.PRODUCTION,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._orders: typing.Optional[OrdersClient] = None
        self._products: typing.Optional[ProductsClient] = None
        self._search: typing.Optional[SearchClient] = None
        self._managed_accounts: typing.Optional[ManagedAccountsClient] = None
        self._agent: typing.Optional[AgentClient] = None
        self._returns: typing.Optional[ReturnsClient] = None
        self._retailers: typing.Optional[RetailersClient] = None
        self._usage: typing.Optional[UsageClient] = None
        self._tracking: typing.Optional[TrackingClient] = None
        self._sandbox: typing.Optional[SandboxClient] = None
        self._health: typing.Optional[HealthClient] = None

    @property
    def orders(self):
        if self._orders is None:
            from .orders.client import OrdersClient  # noqa: E402

            self._orders = OrdersClient(client_wrapper=self._client_wrapper)
        return self._orders

    @property
    def products(self):
        if self._products is None:
            from .products.client import ProductsClient  # noqa: E402

            self._products = ProductsClient(client_wrapper=self._client_wrapper)
        return self._products

    @property
    def search(self):
        if self._search is None:
            from .search.client import SearchClient  # noqa: E402

            self._search = SearchClient(client_wrapper=self._client_wrapper)
        return self._search

    @property
    def managed_accounts(self):
        if self._managed_accounts is None:
            from .managed_accounts.client import ManagedAccountsClient  # noqa: E402

            self._managed_accounts = ManagedAccountsClient(client_wrapper=self._client_wrapper)
        return self._managed_accounts

    @property
    def agent(self):
        if self._agent is None:
            from .agent.client import AgentClient  # noqa: E402

            self._agent = AgentClient(client_wrapper=self._client_wrapper)
        return self._agent

    @property
    def returns(self):
        if self._returns is None:
            from .returns.client import ReturnsClient  # noqa: E402

            self._returns = ReturnsClient(client_wrapper=self._client_wrapper)
        return self._returns

    @property
    def retailers(self):
        if self._retailers is None:
            from .retailers.client import RetailersClient  # noqa: E402

            self._retailers = RetailersClient(client_wrapper=self._client_wrapper)
        return self._retailers

    @property
    def usage(self):
        if self._usage is None:
            from .usage.client import UsageClient  # noqa: E402

            self._usage = UsageClient(client_wrapper=self._client_wrapper)
        return self._usage

    @property
    def tracking(self):
        if self._tracking is None:
            from .tracking.client import TrackingClient  # noqa: E402

            self._tracking = TrackingClient(client_wrapper=self._client_wrapper)
        return self._tracking

    @property
    def sandbox(self):
        if self._sandbox is None:
            from .sandbox.client import SandboxClient  # noqa: E402

            self._sandbox = SandboxClient(client_wrapper=self._client_wrapper)
        return self._sandbox

    @property
    def health(self):
        if self._health is None:
            from .health.client import HealthClient  # noqa: E402

            self._health = HealthClient(client_wrapper=self._client_wrapper)
        return self._health


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncZincioApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : ZincioApiEnvironment
        The environment to use for requests from the client. from .environment import ZincioApiEnvironment



        Defaults to ZincioApiEnvironment.PRODUCTION



    api_key : str
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    stream_reconnection_enabled : typing.Optional[bool]
        Whether to automatically reconnect on stream disconnection for resumable streaming endpoints. Defaults to True. Per-request `stream_reconnection_enabled` in `request_options` takes precedence over this value.

    max_stream_reconnection_attempts : typing.Optional[int]
        The maximum number of reconnection attempts for resumable streaming endpoints. Defaults to no limit. Per-request `max_stream_reconnection_attempts` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from zincio import AsyncZincioApi

    client = AsyncZincioApi(
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: ZincioApiEnvironment = ZincioApiEnvironment.PRODUCTION,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        stream_reconnection_enabled: typing.Optional[bool] = None,
        max_stream_reconnection_attempts: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = timeout if timeout is not None else 60 if httpx_client is None else None
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            stream_reconnection_enabled=stream_reconnection_enabled,
            max_stream_reconnection_attempts=max_stream_reconnection_attempts,
            logging=logging,
        )
        self._orders: typing.Optional[AsyncOrdersClient] = None
        self._products: typing.Optional[AsyncProductsClient] = None
        self._search: typing.Optional[AsyncSearchClient] = None
        self._managed_accounts: typing.Optional[AsyncManagedAccountsClient] = None
        self._agent: typing.Optional[AsyncAgentClient] = None
        self._returns: typing.Optional[AsyncReturnsClient] = None
        self._retailers: typing.Optional[AsyncRetailersClient] = None
        self._usage: typing.Optional[AsyncUsageClient] = None
        self._tracking: typing.Optional[AsyncTrackingClient] = None
        self._sandbox: typing.Optional[AsyncSandboxClient] = None
        self._health: typing.Optional[AsyncHealthClient] = None

    @property
    def orders(self):
        if self._orders is None:
            from .orders.client import AsyncOrdersClient  # noqa: E402

            self._orders = AsyncOrdersClient(client_wrapper=self._client_wrapper)
        return self._orders

    @property
    def products(self):
        if self._products is None:
            from .products.client import AsyncProductsClient  # noqa: E402

            self._products = AsyncProductsClient(client_wrapper=self._client_wrapper)
        return self._products

    @property
    def search(self):
        if self._search is None:
            from .search.client import AsyncSearchClient  # noqa: E402

            self._search = AsyncSearchClient(client_wrapper=self._client_wrapper)
        return self._search

    @property
    def managed_accounts(self):
        if self._managed_accounts is None:
            from .managed_accounts.client import AsyncManagedAccountsClient  # noqa: E402

            self._managed_accounts = AsyncManagedAccountsClient(client_wrapper=self._client_wrapper)
        return self._managed_accounts

    @property
    def agent(self):
        if self._agent is None:
            from .agent.client import AsyncAgentClient  # noqa: E402

            self._agent = AsyncAgentClient(client_wrapper=self._client_wrapper)
        return self._agent

    @property
    def returns(self):
        if self._returns is None:
            from .returns.client import AsyncReturnsClient  # noqa: E402

            self._returns = AsyncReturnsClient(client_wrapper=self._client_wrapper)
        return self._returns

    @property
    def retailers(self):
        if self._retailers is None:
            from .retailers.client import AsyncRetailersClient  # noqa: E402

            self._retailers = AsyncRetailersClient(client_wrapper=self._client_wrapper)
        return self._retailers

    @property
    def usage(self):
        if self._usage is None:
            from .usage.client import AsyncUsageClient  # noqa: E402

            self._usage = AsyncUsageClient(client_wrapper=self._client_wrapper)
        return self._usage

    @property
    def tracking(self):
        if self._tracking is None:
            from .tracking.client import AsyncTrackingClient  # noqa: E402

            self._tracking = AsyncTrackingClient(client_wrapper=self._client_wrapper)
        return self._tracking

    @property
    def sandbox(self):
        if self._sandbox is None:
            from .sandbox.client import AsyncSandboxClient  # noqa: E402

            self._sandbox = AsyncSandboxClient(client_wrapper=self._client_wrapper)
        return self._sandbox

    @property
    def health(self):
        if self._health is None:
            from .health.client import AsyncHealthClient  # noqa: E402

            self._health = AsyncHealthClient(client_wrapper=self._client_wrapper)
        return self._health


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: ZincioApiEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
