# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.address import Address
from ..types.bulk_batch_list_response import BulkBatchListResponse
from ..types.bulk_batch_response import BulkBatchResponse
from ..types.bulk_validate_response import BulkValidateResponse
from ..types.customer_notifications import CustomerNotifications
from ..types.order_list_response import OrderListResponse
from ..types.order_payment import OrderPayment
from ..types.order_product import OrderProduct
from ..types.order_response import OrderResponse
from ..types.order_timeline_response import OrderTimelineResponse
from .raw_client import AsyncRawOrdersClient, RawOrdersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrdersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrdersClient
        """
        return self._raw_client

    def validate_bulk_upload(
        self,
        *,
        authorization: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        rows: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        notify_on_complete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkValidateResponse:
        """
        Dry-run a CSV upload: validate every row and report estimated spend.

        No orders are placed. Use this to show the confirmation preview before
        calling POST /orders/bulk.

        Parameters
        ----------
        authorization : typing.Optional[str]

        filename : typing.Optional[str]
            Original uploaded filename, for display.

        rows : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]
            Parsed CSV rows, each a mapping of column header to cell value.

        notify_on_complete : typing.Optional[bool]
            Email the account holder once every order in this batch has reached a terminal state (placed, failed, or cancelled).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkValidateResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.validate_bulk_upload()
        """
        _response = self._raw_client.validate_bulk_upload(
            authorization=authorization,
            filename=filename,
            rows=rows,
            notify_on_complete=notify_on_complete,
            request_options=request_options,
        )
        return _response.data

    def list_bulk_uploads(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkBatchListResponse:
        """
        List the current user's bulk-upload batches, newest first.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkBatchListResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.list_bulk_uploads()
        """
        _response = self._raw_client.list_bulk_uploads(
            limit=limit, offset=offset, authorization=authorization, request_options=request_options
        )
        return _response.data

    def create_bulk_upload(
        self,
        *,
        authorization: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        rows: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        notify_on_complete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkBatchResponse:
        """
        Create a bulk-upload batch and place its rows asynchronously.

        Parameters
        ----------
        authorization : typing.Optional[str]

        filename : typing.Optional[str]
            Original uploaded filename, for display.

        rows : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]
            Parsed CSV rows, each a mapping of column header to cell value.

        notify_on_complete : typing.Optional[bool]
            Email the account holder once every order in this batch has reached a terminal state (placed, failed, or cancelled).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkBatchResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.create_bulk_upload()
        """
        _response = self._raw_client.create_bulk_upload(
            authorization=authorization,
            filename=filename,
            rows=rows,
            notify_on_complete=notify_on_complete,
            request_options=request_options,
        )
        return _response.data

    def get_bulk_upload(
        self,
        batch_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkBatchResponse:
        """
        Get a batch with per-row results and live order statuses.

        Parameters
        ----------
        batch_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkBatchResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.get_bulk_upload(
            batch_id="batch_id",
        )
        """
        _response = self._raw_client.get_bulk_upload(
            batch_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    def download_bulk_results(
        self,
        batch_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> str:
        """
        Download the batch results as a CSV (status + echoed custom columns).

        Parameters
        ----------
        batch_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            CSV export: one row per uploaded row, with its order status and any echoed custom columns. Served as an attachment via Content-Disposition.

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.download_bulk_results(
            batch_id="batch_id",
        )
        """
        _response = self._raw_client.download_bulk_results(
            batch_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    def list_orders(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        order_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        merchant_order_id: typing.Optional[str] = None,
        status_filter: typing.Optional[str] = None,
        tracking_status: typing.Optional[str] = None,
        has_tracking: typing.Optional[bool] = None,
        return_status: typing.Optional[str] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        metadata_key: typing.Optional[str] = None,
        metadata_value: typing.Optional[str] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderListResponse:
        """
        Get a list of orders for the current user

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of orders to return

        offset : typing.Optional[int]
            Number of orders to skip

        order_id : typing.Optional[str]
            Filter by order ID (partial match)

        search : typing.Optional[str]
            Partial match on order ID OR tracking number

        merchant_order_id : typing.Optional[str]
            Filter by the retailer's own order number (e.g. an Amazon `113-…` ID), matched exactly against any of the order's order-placing jobs. Exact, not partial — dashes in the term are matched both as typed and stripped.

        status_filter : typing.Optional[str]
            Filter by order status

        tracking_status : typing.Optional[str]
            Filter to orders having at least one tracking number with this status

        has_tracking : typing.Optional[bool]
            If true, only orders with at least one tracking number; if false, only orders with none

        return_status : typing.Optional[str]
            Filter by return-request status. `open` → orders with at least one open return. `closed` → orders with at least one approved or denied return. Omit for no filter.

        created_after : typing.Optional[dt.datetime]
            Only orders created at/after this instant (inclusive)

        created_before : typing.Optional[dt.datetime]
            Only orders created before this instant (exclusive)

        metadata_key : typing.Optional[str]
            Top-level `metadata` key to match, e.g. `po_number`. Must be sent together with `metadata_value`. Nested paths are not supported.

        metadata_value : typing.Optional[str]
            Exact value `metadata_key` must equal. Matching is exact, not partial, and case-sensitive. Must be sent together with `metadata_key`.

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Optional expansions. `tracking_events` embeds the full carrier checkpoint timeline (and latest status) on each tracking number; omitted by default to keep list payloads small.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderListResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.list_orders()
        """
        _response = self._raw_client.list_orders(
            limit=limit,
            offset=offset,
            order_id=order_id,
            search=search,
            merchant_order_id=merchant_order_id,
            status_filter=status_filter,
            tracking_status=tracking_status,
            has_tracking=has_tracking,
            return_status=return_status,
            created_after=created_after,
            created_before=created_before,
            metadata_key=metadata_key,
            metadata_value=metadata_value,
            include=include,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    def create_order(
        self,
        *,
        products: typing.Sequence[OrderProduct],
        shipping_address: Address,
        max_price: int,
        authorization: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = OMIT,
        retailer_credentials_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        po_number: typing.Optional[str] = OMIT,
        handling_days_max: typing.Optional[int] = OMIT,
        is_gift: typing.Optional[bool] = OMIT,
        gift_message: typing.Optional[str] = OMIT,
        payment: typing.Optional[OrderPayment] = OMIT,
        customer_notifications: typing.Optional[CustomerNotifications] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderResponse:
        """
        Posts an order to a queue for processing

        Parameters
        ----------
        products : typing.Sequence[OrderProduct]

        shipping_address : Address

        max_price : int
            Maximum price (in cents) allowed for an order before it is finalized.

        authorization : typing.Optional[str]

        idempotency_key : typing.Optional[str]
            Optional idempotency key to prevent duplicate orders. If not provided, one will be generated.

        retailer_credentials_id : typing.Optional[str]
            Optional short ID (e.g., 'zn_acct_XXXXXXXX') of specific retailer credentials to use for this order. If not provided, credentials will be selected automatically.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Optional metadata to attach to the order. Can contain arbitrary key-value pairs.

        po_number : typing.Optional[str]
            Optional purchase order number for the order.

        handling_days_max : typing.Optional[int]
            Optional ceiling on a seller's shipping and handling days. Omit or send null for no limit.

        is_gift : typing.Optional[bool]
            Mark the order as a gift, suppressing prices on the packing slip. If the retailer's checkout offers no free gift option, the order FAILS with `gift_option_unavailable` rather than being placed as a normal order — a gift that arrives with prices visible to the recipient is treated as worse than no order.

        gift_message : typing.Optional[str]
            Optional note for the recipient, entered into the retailer's gift-message field at checkout. Requires `is_gift` to be true. Max 240 characters. Delivered where the retailer's checkout offers a gift message; the order is still placed without it where one isn't available.

        payment : typing.Optional[OrderPayment]
            Optional payment block. Omit for prepaid-wallet billing (default).

        customer_notifications : typing.Optional[CustomerNotifications]
            Opt in to emailing the end customer order updates (and unlock the public tracking page for this order). Adds a per-order surcharge. Omit for no customer notifications (default).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderResponse
            Successful Response

        Examples
        --------
        from zinc import Address, OrderProduct, ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.create_order(
            products=[
                OrderProduct(
                    url="https://www.amazon.com/dp/B07JGBW826",
                )
            ],
            shipping_address=Address(
                first_name="first_name",
                last_name="last_name",
                address_line1="address_line1",
                city="city",
                postal_code="postal_code",
                phone_number="phone_number",
            ),
            max_price=1,
        )
        """
        _response = self._raw_client.create_order(
            products=products,
            shipping_address=shipping_address,
            max_price=max_price,
            authorization=authorization,
            idempotency_key=idempotency_key,
            retailer_credentials_id=retailer_credentials_id,
            metadata=metadata,
            po_number=po_number,
            handling_days_max=handling_days_max,
            is_gift=is_gift,
            gift_message=gift_message,
            payment=payment,
            customer_notifications=customer_notifications,
            request_options=request_options,
        )
        return _response.data

    def list_test_products(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get list of test products for sandbox testing.

        Returns list of test product URLs that can be used with test API keys
        to trigger different test scenarios.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.list_test_products()
        """
        _response = self._raw_client.list_test_products(request_options=request_options)
        return _response.data

    def get_order(
        self,
        order_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderResponse:
        """
        Retrieves an order by its ID

        Parameters
        ----------
        order_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.get_order(
            order_id="order_id",
        )
        """
        _response = self._raw_client.get_order(order_id, authorization=authorization, request_options=request_options)
        return _response.data

    def get_order_timeline(
        self,
        order_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderTimelineResponse:
        """
        Customer-facing lifecycle timeline for an order.

        Derived on read from existing data — no dedicated storage. Merges the
        placement outcome (OrderLog) with carrier tracking state (TrackingNumber /
        TrackingCheckpoint) into an ordered list of milestones. This is the order's
        story to the customer, distinct from the admin-only job/automation log.

        Parameters
        ----------
        order_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderTimelineResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.get_order_timeline(
            order_id="order_id",
        )
        """
        _response = self._raw_client.get_order_timeline(
            order_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    def cancel_order(
        self,
        order_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Cancel an order by its ID. Orders can only be cancelled if they are pending.

        Parameters
        ----------
        order_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.orders.cancel_order(
            order_id="order_id",
        )
        """
        _response = self._raw_client.cancel_order(
            order_id, authorization=authorization, request_options=request_options
        )
        return _response.data


class AsyncOrdersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrdersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrdersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrdersClient
        """
        return self._raw_client

    async def validate_bulk_upload(
        self,
        *,
        authorization: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        rows: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        notify_on_complete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkValidateResponse:
        """
        Dry-run a CSV upload: validate every row and report estimated spend.

        No orders are placed. Use this to show the confirmation preview before
        calling POST /orders/bulk.

        Parameters
        ----------
        authorization : typing.Optional[str]

        filename : typing.Optional[str]
            Original uploaded filename, for display.

        rows : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]
            Parsed CSV rows, each a mapping of column header to cell value.

        notify_on_complete : typing.Optional[bool]
            Email the account holder once every order in this batch has reached a terminal state (placed, failed, or cancelled).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkValidateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.validate_bulk_upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_bulk_upload(
            authorization=authorization,
            filename=filename,
            rows=rows,
            notify_on_complete=notify_on_complete,
            request_options=request_options,
        )
        return _response.data

    async def list_bulk_uploads(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkBatchListResponse:
        """
        List the current user's bulk-upload batches, newest first.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkBatchListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.list_bulk_uploads()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_bulk_uploads(
            limit=limit, offset=offset, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def create_bulk_upload(
        self,
        *,
        authorization: typing.Optional[str] = None,
        filename: typing.Optional[str] = OMIT,
        rows: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        notify_on_complete: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkBatchResponse:
        """
        Create a bulk-upload batch and place its rows asynchronously.

        Parameters
        ----------
        authorization : typing.Optional[str]

        filename : typing.Optional[str]
            Original uploaded filename, for display.

        rows : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]
            Parsed CSV rows, each a mapping of column header to cell value.

        notify_on_complete : typing.Optional[bool]
            Email the account holder once every order in this batch has reached a terminal state (placed, failed, or cancelled).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkBatchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.create_bulk_upload()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_bulk_upload(
            authorization=authorization,
            filename=filename,
            rows=rows,
            notify_on_complete=notify_on_complete,
            request_options=request_options,
        )
        return _response.data

    async def get_bulk_upload(
        self,
        batch_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BulkBatchResponse:
        """
        Get a batch with per-row results and live order statuses.

        Parameters
        ----------
        batch_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkBatchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.get_bulk_upload(
                batch_id="batch_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_bulk_upload(
            batch_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def download_bulk_results(
        self,
        batch_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> str:
        """
        Download the batch results as a CSV (status + echoed custom columns).

        Parameters
        ----------
        batch_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            CSV export: one row per uploaded row, with its order status and any echoed custom columns. Served as an attachment via Content-Disposition.

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.download_bulk_results(
                batch_id="batch_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.download_bulk_results(
            batch_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def list_orders(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        order_id: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        merchant_order_id: typing.Optional[str] = None,
        status_filter: typing.Optional[str] = None,
        tracking_status: typing.Optional[str] = None,
        has_tracking: typing.Optional[bool] = None,
        return_status: typing.Optional[str] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        metadata_key: typing.Optional[str] = None,
        metadata_value: typing.Optional[str] = None,
        include: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderListResponse:
        """
        Get a list of orders for the current user

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of orders to return

        offset : typing.Optional[int]
            Number of orders to skip

        order_id : typing.Optional[str]
            Filter by order ID (partial match)

        search : typing.Optional[str]
            Partial match on order ID OR tracking number

        merchant_order_id : typing.Optional[str]
            Filter by the retailer's own order number (e.g. an Amazon `113-…` ID), matched exactly against any of the order's order-placing jobs. Exact, not partial — dashes in the term are matched both as typed and stripped.

        status_filter : typing.Optional[str]
            Filter by order status

        tracking_status : typing.Optional[str]
            Filter to orders having at least one tracking number with this status

        has_tracking : typing.Optional[bool]
            If true, only orders with at least one tracking number; if false, only orders with none

        return_status : typing.Optional[str]
            Filter by return-request status. `open` → orders with at least one open return. `closed` → orders with at least one approved or denied return. Omit for no filter.

        created_after : typing.Optional[dt.datetime]
            Only orders created at/after this instant (inclusive)

        created_before : typing.Optional[dt.datetime]
            Only orders created before this instant (exclusive)

        metadata_key : typing.Optional[str]
            Top-level `metadata` key to match, e.g. `po_number`. Must be sent together with `metadata_value`. Nested paths are not supported.

        metadata_value : typing.Optional[str]
            Exact value `metadata_key` must equal. Matching is exact, not partial, and case-sensitive. Must be sent together with `metadata_key`.

        include : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Optional expansions. `tracking_events` embeds the full carrier checkpoint timeline (and latest status) on each tracking number; omitted by default to keep list payloads small.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.list_orders()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_orders(
            limit=limit,
            offset=offset,
            order_id=order_id,
            search=search,
            merchant_order_id=merchant_order_id,
            status_filter=status_filter,
            tracking_status=tracking_status,
            has_tracking=has_tracking,
            return_status=return_status,
            created_after=created_after,
            created_before=created_before,
            metadata_key=metadata_key,
            metadata_value=metadata_value,
            include=include,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    async def create_order(
        self,
        *,
        products: typing.Sequence[OrderProduct],
        shipping_address: Address,
        max_price: int,
        authorization: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = OMIT,
        retailer_credentials_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        po_number: typing.Optional[str] = OMIT,
        handling_days_max: typing.Optional[int] = OMIT,
        is_gift: typing.Optional[bool] = OMIT,
        gift_message: typing.Optional[str] = OMIT,
        payment: typing.Optional[OrderPayment] = OMIT,
        customer_notifications: typing.Optional[CustomerNotifications] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderResponse:
        """
        Posts an order to a queue for processing

        Parameters
        ----------
        products : typing.Sequence[OrderProduct]

        shipping_address : Address

        max_price : int
            Maximum price (in cents) allowed for an order before it is finalized.

        authorization : typing.Optional[str]

        idempotency_key : typing.Optional[str]
            Optional idempotency key to prevent duplicate orders. If not provided, one will be generated.

        retailer_credentials_id : typing.Optional[str]
            Optional short ID (e.g., 'zn_acct_XXXXXXXX') of specific retailer credentials to use for this order. If not provided, credentials will be selected automatically.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Optional metadata to attach to the order. Can contain arbitrary key-value pairs.

        po_number : typing.Optional[str]
            Optional purchase order number for the order.

        handling_days_max : typing.Optional[int]
            Optional ceiling on a seller's shipping and handling days. Omit or send null for no limit.

        is_gift : typing.Optional[bool]
            Mark the order as a gift, suppressing prices on the packing slip. If the retailer's checkout offers no free gift option, the order FAILS with `gift_option_unavailable` rather than being placed as a normal order — a gift that arrives with prices visible to the recipient is treated as worse than no order.

        gift_message : typing.Optional[str]
            Optional note for the recipient, entered into the retailer's gift-message field at checkout. Requires `is_gift` to be true. Max 240 characters. Delivered where the retailer's checkout offers a gift message; the order is still placed without it where one isn't available.

        payment : typing.Optional[OrderPayment]
            Optional payment block. Omit for prepaid-wallet billing (default).

        customer_notifications : typing.Optional[CustomerNotifications]
            Opt in to emailing the end customer order updates (and unlock the public tracking page for this order). Adds a per-order surcharge. Omit for no customer notifications (default).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import Address, AsyncZincClient, OrderProduct

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.create_order(
                products=[
                    OrderProduct(
                        url="https://www.amazon.com/dp/B07JGBW826",
                    )
                ],
                shipping_address=Address(
                    first_name="first_name",
                    last_name="last_name",
                    address_line1="address_line1",
                    city="city",
                    postal_code="postal_code",
                    phone_number="phone_number",
                ),
                max_price=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_order(
            products=products,
            shipping_address=shipping_address,
            max_price=max_price,
            authorization=authorization,
            idempotency_key=idempotency_key,
            retailer_credentials_id=retailer_credentials_id,
            metadata=metadata,
            po_number=po_number,
            handling_days_max=handling_days_max,
            is_gift=is_gift,
            gift_message=gift_message,
            payment=payment,
            customer_notifications=customer_notifications,
            request_options=request_options,
        )
        return _response.data

    async def list_test_products(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get list of test products for sandbox testing.

        Returns list of test product URLs that can be used with test API keys
        to trigger different test scenarios.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.list_test_products()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_test_products(request_options=request_options)
        return _response.data

    async def get_order(
        self,
        order_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderResponse:
        """
        Retrieves an order by its ID

        Parameters
        ----------
        order_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.get_order(
                order_id="order_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_order(
            order_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def get_order_timeline(
        self,
        order_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrderTimelineResponse:
        """
        Customer-facing lifecycle timeline for an order.

        Derived on read from existing data — no dedicated storage. Merges the
        placement outcome (OrderLog) with carrier tracking state (TrackingNumber /
        TrackingCheckpoint) into an ordered list of milestones. This is the order's
        story to the customer, distinct from the admin-only job/automation log.

        Parameters
        ----------
        order_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrderTimelineResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.get_order_timeline(
                order_id="order_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_order_timeline(
            order_id, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def cancel_order(
        self,
        order_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Cancel an order by its ID. Orders can only be cancelled if they are pending.

        Parameters
        ----------
        order_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.orders.cancel_order(
                order_id="order_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_order(
            order_id, authorization=authorization, request_options=request_options
        )
        return _response.data
