# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.wallet_response import WalletResponse
from pydantic import ValidationError


class RawWalletClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_wallet(
        self, *, authorization: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WalletResponse]:
        """
        Get your wallet balance.

        All amounts are integer cents. `balance` is the ledger balance;
        `spendable_balance` is what `POST /orders` actually checks against (the two
        differ only for Zinc Connect accounts with in-flight holds). An order needs
        `max_price + order_fee_cents` spendable, so compare against that before
        placing one instead of discovering a shortfall as a 402. Bulk-deal customers
        (`billed_by_invoice: true`) are invoiced monthly and skip the balance check.

        Under a `zn_test_` key (or `X-Test-Mode`) this reads the sandbox wallet,
        which sandbox orders never draw down. Funds are added from the dashboard.

        Parameters
        ----------
        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WalletResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "wallet/me",
            method="GET",
            headers={
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WalletResponse,
                    parse_obj_as(
                        type_=WalletResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWalletClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_wallet(
        self, *, authorization: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WalletResponse]:
        """
        Get your wallet balance.

        All amounts are integer cents. `balance` is the ledger balance;
        `spendable_balance` is what `POST /orders` actually checks against (the two
        differ only for Zinc Connect accounts with in-flight holds). An order needs
        `max_price + order_fee_cents` spendable, so compare against that before
        placing one instead of discovering a shortfall as a 402. Bulk-deal customers
        (`billed_by_invoice: true`) are invoiced monthly and skip the balance check.

        Under a `zn_test_` key (or `X-Test-Mode`) this reads the sandbox wallet,
        which sandbox orders never draw down. Funds are added from the dashboard.

        Parameters
        ----------
        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WalletResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "wallet/me",
            method="GET",
            headers={
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WalletResponse,
                    parse_obj_as(
                        type_=WalletResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
