# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.product_search_response import ProductSearchResponse
from .raw_client import AsyncRawProductsClient, RawProductsClient
from .types.get_product_details_products_product_id_get_request_retailer import (
    GetProductDetailsProductsProductIdGetRequestRetailer,
)
from .types.get_product_offers_products_product_id_offers_get_request_retailer import (
    GetProductOffersProductsProductIdOffersGetRequestRetailer,
)
from .types.search_products_products_search_get_request_retailer import SearchProductsProductsSearchGetRequestRetailer


class ProductsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProductsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProductsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProductsClient
        """
        return self._raw_client

    def search_products(
        self,
        *,
        query: str,
        retailer: SearchProductsProductsSearchGetRequestRetailer,
        page: typing.Optional[int] = None,
        free_shipping: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductSearchResponse:
        """
        Search for products on a retailer.

        Parameters
        ----------
        query : str
            Search term

        retailer : SearchProductsProductsSearchGetRequestRetailer
            Retailer identifier

        page : typing.Optional[int]
            Page number for pagination

        free_shipping : typing.Optional[bool]
            Only return items that ship for free (Walmart: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so filtering on it would drop valid items — Amazon results are returned unfiltered. Filtering happens after v1 pagination, so per-page counts vary; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductSearchResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.products.search_products(
            query="query",
            retailer="amazon",
        )
        """
        _response = self._raw_client.search_products(
            query=query,
            retailer=retailer,
            page=page,
            free_shipping=free_shipping,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    def get_product_offers(
        self,
        product_id: str,
        *,
        retailer: GetProductOffersProductsProductIdOffersGetRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Get offers for a product from a retailer.

        Parameters
        ----------
        product_id : str

        retailer : GetProductOffersProductsProductIdOffersGetRequestRetailer
            Retailer identifier

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.products.get_product_offers(
            product_id="product_id",
            retailer="amazon",
        )
        """
        _response = self._raw_client.get_product_offers(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    def get_product_details(
        self,
        product_id: str,
        *,
        retailer: GetProductDetailsProductsProductIdGetRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Get details for a product from a retailer.

        Parameters
        ----------
        product_id : str

        retailer : GetProductDetailsProductsProductIdGetRequestRetailer
            Retailer identifier

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.products.get_product_details(
            product_id="product_id",
            retailer="amazon",
        )
        """
        _response = self._raw_client.get_product_details(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data


class AsyncProductsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProductsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProductsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProductsClient
        """
        return self._raw_client

    async def search_products(
        self,
        *,
        query: str,
        retailer: SearchProductsProductsSearchGetRequestRetailer,
        page: typing.Optional[int] = None,
        free_shipping: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductSearchResponse:
        """
        Search for products on a retailer.

        Parameters
        ----------
        query : str
            Search term

        retailer : SearchProductsProductsSearchGetRequestRetailer
            Retailer identifier

        page : typing.Optional[int]
            Page number for pagination

        free_shipping : typing.Optional[bool]
            Only return items that ship for free (Walmart: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so filtering on it would drop valid items — Amazon results are returned unfiltered. Filtering happens after v1 pagination, so per-page counts vary; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductSearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.search_products(
                query="query",
                retailer="amazon",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_products(
            query=query,
            retailer=retailer,
            page=page,
            free_shipping=free_shipping,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    async def get_product_offers(
        self,
        product_id: str,
        *,
        retailer: GetProductOffersProductsProductIdOffersGetRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Get offers for a product from a retailer.

        Parameters
        ----------
        product_id : str

        retailer : GetProductOffersProductsProductIdOffersGetRequestRetailer
            Retailer identifier

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.get_product_offers(
                product_id="product_id",
                retailer="amazon",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_product_offers(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    async def get_product_details(
        self,
        product_id: str,
        *,
        retailer: GetProductDetailsProductsProductIdGetRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Get details for a product from a retailer.

        Parameters
        ----------
        product_id : str

        retailer : GetProductDetailsProductsProductIdGetRequestRetailer
            Retailer identifier

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.get_product_details(
                product_id="product_id",
                retailer="amazon",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_product_details(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data
