# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.sandbox_claim_response import SandboxClaimResponse
from ..types.sandbox_key_create import SandboxKeyCreate
from ..types.sandbox_key_response import SandboxKeyResponse
from ..types.sandbox_status_response import SandboxStatusResponse
from .raw_client import AsyncRawSandboxClient, RawSandboxClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxClient
        """
        return self._raw_client

    def create_sandbox_key(
        self,
        *,
        request: typing.Optional[SandboxKeyCreate] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxKeyResponse:
        """
        Mint a provisional sandbox user + test API key. No account needed.

        Parameters
        ----------
        request : typing.Optional[SandboxKeyCreate]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxKeyResponse
            Sandbox key minted. The body is self-guiding: send `api_key` as a Bearer token, POST `example_order` to /orders as-is, and follow `next`.

        Examples
        --------
        from zincio import SandboxKeyCreate, ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.create_sandbox_key(
            request=SandboxKeyCreate(),
        )
        """
        _response = self._raw_client.create_sandbox_key(request=request, request_options=request_options)
        return _response.data

    def claim_sandbox(
        self,
        *,
        token: str,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxClaimResponse:
        """
        Fold a provisional sandbox into the authenticated account.

        Always a merge: Stytch's callback creates a real user row on first login,
        so a caller reaching this endpoint already has an account. The agent's key
        is reassigned rather than revoked, so whatever it has hardcoded keeps
        working — that is the point of claiming rather than starting over.

        Parameters
        ----------
        token : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxClaimResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.claim_sandbox(
            token="token",
        )
        """
        _response = self._raw_client.claim_sandbox(
            token=token, authorization=authorization, request_options=request_options
        )
        return _response.data

    def get_sandbox_status(
        self, *, authorization: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxStatusResponse:
        """
        Whether the sandbox this key belongs to has been claimed yet.

        An agent hands its claim URL to a human and then has no way to learn what
        happened — a device-code grant would tell it for free (issue #825). Until
        we have one, polling this closes the loop.

        Still provisional means nobody has claimed it. Past that, "not provisional"
        alone would be a lie — every ordinary account would read as claimed — so
        the answer comes from the claim event written on the account, which is
        also the only durable evidence a claim happened once the provisional row
        is deleted.

        Parameters
        ----------
        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxStatusResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.get_sandbox_status()
        """
        _response = self._raw_client.get_sandbox_status(authorization=authorization, request_options=request_options)
        return _response.data

    def get_quickstart(self, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        The agent quickstart, served as plain markdown.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            The agent quickstart as plain markdown: mint a key, place a sandbox order, watch the lifecycle, rehearse each failure mode, go live.

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.sandbox.get_quickstart()
        """
        _response = self._raw_client.get_quickstart(request_options=request_options)
        return _response.data


class AsyncSandboxClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxClient
        """
        return self._raw_client

    async def create_sandbox_key(
        self,
        *,
        request: typing.Optional[SandboxKeyCreate] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxKeyResponse:
        """
        Mint a provisional sandbox user + test API key. No account needed.

        Parameters
        ----------
        request : typing.Optional[SandboxKeyCreate]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxKeyResponse
            Sandbox key minted. The body is self-guiding: send `api_key` as a Bearer token, POST `example_order` to /orders as-is, and follow `next`.

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi, SandboxKeyCreate

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.create_sandbox_key(
                request=SandboxKeyCreate(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_sandbox_key(request=request, request_options=request_options)
        return _response.data

    async def claim_sandbox(
        self,
        *,
        token: str,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxClaimResponse:
        """
        Fold a provisional sandbox into the authenticated account.

        Always a merge: Stytch's callback creates a real user row on first login,
        so a caller reaching this endpoint already has an account. The agent's key
        is reassigned rather than revoked, so whatever it has hardcoded keeps
        working — that is the point of claiming rather than starting over.

        Parameters
        ----------
        token : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxClaimResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.claim_sandbox(
                token="token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.claim_sandbox(
            token=token, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def get_sandbox_status(
        self, *, authorization: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> SandboxStatusResponse:
        """
        Whether the sandbox this key belongs to has been claimed yet.

        An agent hands its claim URL to a human and then has no way to learn what
        happened — a device-code grant would tell it for free (issue #825). Until
        we have one, polling this closes the loop.

        Still provisional means nobody has claimed it. Past that, "not provisional"
        alone would be a lie — every ordinary account would read as claimed — so
        the answer comes from the claim event written on the account, which is
        also the only durable evidence a claim happened once the provisional row
        is deleted.

        Parameters
        ----------
        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxStatusResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.get_sandbox_status()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sandbox_status(
            authorization=authorization, request_options=request_options
        )
        return _response.data

    async def get_quickstart(self, *, request_options: typing.Optional[RequestOptions] = None) -> str:
        """
        The agent quickstart, served as plain markdown.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        str
            The agent quickstart as plain markdown: mint a key, place a sandbox order, watch the lifecycle, rehearse each failure mode, go live.

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandbox.get_quickstart()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_quickstart(request_options=request_options)
        return _response.data
