# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.delivery_map_response import DeliveryMapResponse
from ..types.lifetime_stats_response import LifetimeStatsResponse
from .raw_client import AsyncRawStatsClient, RawStatsClient


class StatsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStatsClient
        """
        return self._raw_client

    def get_delivery_map(self, *, request_options: typing.Optional[RequestOptions] = None) -> DeliveryMapResponse:
        """
        Recent delivered orders as anonymized, city-level map points.

        Public and unauthenticated — feeds the marketing site's globe. Points are
        ZIP-centroid coordinates rounded to two decimals with a curated category
        emoji; deduplicated and capped. Cached for about an hour.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeliveryMapResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.stats.get_delivery_map()
        """
        _response = self._raw_client.get_delivery_map(request_options=request_options)
        return _response.data

    def get_lifetime_stats(self, *, request_options: typing.Optional[RequestOptions] = None) -> LifetimeStatsResponse:
        """
        Zinc's all-time successful-order count and GMV.

        Public and unauthenticated. Top-level numbers are v2 (this service);
        ``v1`` is the worker-computed legacy snapshot (seed until the first
        compute lands); ``combined`` sums both. Cached for about a day.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LifetimeStatsResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.stats.get_lifetime_stats()
        """
        _response = self._raw_client.get_lifetime_stats(request_options=request_options)
        return _response.data


class AsyncStatsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStatsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStatsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStatsClient
        """
        return self._raw_client

    async def get_delivery_map(self, *, request_options: typing.Optional[RequestOptions] = None) -> DeliveryMapResponse:
        """
        Recent delivered orders as anonymized, city-level map points.

        Public and unauthenticated — feeds the marketing site's globe. Points are
        ZIP-centroid coordinates rounded to two decimals with a curated category
        emoji; deduplicated and capped. Cached for about an hour.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeliveryMapResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.stats.get_delivery_map()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_delivery_map(request_options=request_options)
        return _response.data

    async def get_lifetime_stats(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LifetimeStatsResponse:
        """
        Zinc's all-time successful-order count and GMV.

        Public and unauthenticated. Top-level numbers are v2 (this service);
        ``v1`` is the worker-computed legacy snapshot (seed until the first
        compute lands); ``combined`` sums both. Cached for about a day.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LifetimeStatsResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.stats.get_lifetime_stats()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_lifetime_stats(request_options=request_options)
        return _response.data
