# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.search_response import SearchResponse
from ..types.search_retailer import SearchRetailer
from ..types.search_sort import SearchSort
from .raw_client import AsyncRawSearchClient, RawSearchClient


class SearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchClient
        """
        return self._raw_client

    def search(
        self,
        *,
        q: str,
        min_price: typing.Optional[int] = None,
        max_price: typing.Optional[int] = None,
        retailer: typing.Optional[typing.Sequence[SearchRetailer]] = None,
        sort: typing.Optional[SearchSort] = None,
        limit: typing.Optional[int] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Search for products across retailers; returns orderable zn_sku_ listings.

        **Billing.** This is a metered data call: $0.01 is drawn from your wallet per successful request, before any order is placed. An empty wallet gets `402` instead. Sandbox (`zn_test_`) calls are free and never touch the live wallet.

        Parameters
        ----------
        q : str
            Search term

        min_price : typing.Optional[int]
            Cents. Drop results priced below this.

        max_price : typing.Optional[int]
            Cents. Drop results priced above this. Pass the `max_price` you intend to send to POST /orders and every result returned fits it. Results with no known price are dropped when a clamp is set.

        retailer : typing.Optional[typing.Sequence[SearchRetailer]]
            Only return results from these retailers. Repeat the param for several: `?retailer=amazon&retailer=target`.

        sort : typing.Optional[SearchSort]
            Result order. `relevance` (default) blends query match, source rank and rating, and mixes retailers. The explicit sorts order the 20 most relevant results (or `limit`, if larger) that match at least half the query, so accessories that merely name the product don't lead; results with no price (or no rating, for `rating`) sort last.

        limit : typing.Optional[int]
            Return at most this many results (1-50). One search is one billed call either way.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.search.search(
            q="q",
        )
        """
        _response = self._raw_client.search(
            q=q,
            min_price=min_price,
            max_price=max_price,
            retailer=retailer,
            sort=sort,
            limit=limit,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data


class AsyncSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        q: str,
        min_price: typing.Optional[int] = None,
        max_price: typing.Optional[int] = None,
        retailer: typing.Optional[typing.Sequence[SearchRetailer]] = None,
        sort: typing.Optional[SearchSort] = None,
        limit: typing.Optional[int] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Search for products across retailers; returns orderable zn_sku_ listings.

        **Billing.** This is a metered data call: $0.01 is drawn from your wallet per successful request, before any order is placed. An empty wallet gets `402` instead. Sandbox (`zn_test_`) calls are free and never touch the live wallet.

        Parameters
        ----------
        q : str
            Search term

        min_price : typing.Optional[int]
            Cents. Drop results priced below this.

        max_price : typing.Optional[int]
            Cents. Drop results priced above this. Pass the `max_price` you intend to send to POST /orders and every result returned fits it. Results with no known price are dropped when a clamp is set.

        retailer : typing.Optional[typing.Sequence[SearchRetailer]]
            Only return results from these retailers. Repeat the param for several: `?retailer=amazon&retailer=target`.

        sort : typing.Optional[SearchSort]
            Result order. `relevance` (default) blends query match, source rank and rating, and mixes retailers. The explicit sorts order the 20 most relevant results (or `limit`, if larger) that match at least half the query, so accessories that merely name the product don't lead; results with no price (or no rating, for `rating`) sort last.

        limit : typing.Optional[int]
            Return at most this many results (1-50). One search is one billed call either way.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.search.search(
                q="q",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            q=q,
            min_price=min_price,
            max_price=max_price,
            retailer=retailer,
            sort=sort,
            limit=limit,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data
