# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.retailer_credentials_list_response import RetailerCredentialsListResponse
from ..types.retailer_credentials_response import RetailerCredentialsResponse
from .raw_client import AsyncRawManagedAccountsClient, RawManagedAccountsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ManagedAccountsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawManagedAccountsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawManagedAccountsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawManagedAccountsClient
        """
        return self._raw_client

    def list_retailer_credentials(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetailerCredentialsListResponse:
        """
        List all retailer credentials for the current user.
        If is_global=True (admin only), list global credentials instead.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size (default 50, max 500). Responses include `total` for paging past it.

        offset : typing.Optional[int]
            Number of credentials to skip

        search : typing.Optional[str]
            Partial match on email or retailer

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetailerCredentialsListResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.managed_accounts.list_retailer_credentials()
        """
        _response = self._raw_client.list_retailer_credentials(
            limit=limit, offset=offset, search=search, authorization=authorization, request_options=request_options
        )
        return _response.data

    def create_retailer_credentials(
        self,
        *,
        email: str,
        authorization: typing.Optional[str] = None,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetailerCredentialsResponse:
        """
        Create new retailer credentials for the current user.
        If is_global=True (admin only), creates global credentials owned by the system user.

        Parameters
        ----------
        email : str

        authorization : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]
            Retailer name (e.g., 'amazon'). If null, applies as default credentials.

        totp_secret : typing.Optional[str]
            TOTP secret key for 2FA (will be encrypted at rest).

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetailerCredentialsResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.managed_accounts.create_retailer_credentials(
            email="email",
        )
        """
        _response = self._raw_client.create_retailer_credentials(
            email=email,
            authorization=authorization,
            password=password,
            retailer=retailer,
            totp_secret=totp_secret,
            retailer_config=retailer_config,
            request_options=request_options,
        )
        return _response.data

    def update_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        email: typing.Optional[str] = OMIT,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetailerCredentialsResponse:
        """
        Update retailer credentials for the current user.
        Admins can also update global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        email : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]

        totp_secret : typing.Optional[str]

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetailerCredentialsResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.managed_accounts.update_retailer_credentials(
            short_id="short_id",
        )
        """
        _response = self._raw_client.update_retailer_credentials(
            short_id,
            authorization=authorization,
            email=email,
            password=password,
            retailer=retailer,
            totp_secret=totp_secret,
            retailer_config=retailer_config,
            request_options=request_options,
        )
        return _response.data

    def delete_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete retailer credentials for the current user.
        Admins can also delete global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.managed_accounts.delete_retailer_credentials(
            short_id="short_id",
        )
        """
        _response = self._raw_client.delete_retailer_credentials(
            short_id, authorization=authorization, request_options=request_options
        )
        return _response.data


class AsyncManagedAccountsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawManagedAccountsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawManagedAccountsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawManagedAccountsClient
        """
        return self._raw_client

    async def list_retailer_credentials(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetailerCredentialsListResponse:
        """
        List all retailer credentials for the current user.
        If is_global=True (admin only), list global credentials instead.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size (default 50, max 500). Responses include `total` for paging past it.

        offset : typing.Optional[int]
            Number of credentials to skip

        search : typing.Optional[str]
            Partial match on email or retailer

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetailerCredentialsListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_accounts.list_retailer_credentials()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_retailer_credentials(
            limit=limit, offset=offset, search=search, authorization=authorization, request_options=request_options
        )
        return _response.data

    async def create_retailer_credentials(
        self,
        *,
        email: str,
        authorization: typing.Optional[str] = None,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetailerCredentialsResponse:
        """
        Create new retailer credentials for the current user.
        If is_global=True (admin only), creates global credentials owned by the system user.

        Parameters
        ----------
        email : str

        authorization : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]
            Retailer name (e.g., 'amazon'). If null, applies as default credentials.

        totp_secret : typing.Optional[str]
            TOTP secret key for 2FA (will be encrypted at rest).

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetailerCredentialsResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_accounts.create_retailer_credentials(
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_retailer_credentials(
            email=email,
            authorization=authorization,
            password=password,
            retailer=retailer,
            totp_secret=totp_secret,
            retailer_config=retailer_config,
            request_options=request_options,
        )
        return _response.data

    async def update_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        email: typing.Optional[str] = OMIT,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetailerCredentialsResponse:
        """
        Update retailer credentials for the current user.
        Admins can also update global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        email : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]

        totp_secret : typing.Optional[str]

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetailerCredentialsResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_accounts.update_retailer_credentials(
                short_id="short_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_retailer_credentials(
            short_id,
            authorization=authorization,
            email=email,
            password=password,
            retailer=retailer,
            totp_secret=totp_secret,
            retailer_config=retailer_config,
            request_options=request_options,
        )
        return _response.data

    async def delete_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Delete retailer credentials for the current user.
        Admins can also delete global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.managed_accounts.delete_retailer_credentials(
                short_id="short_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_retailer_credentials(
            short_id, authorization=authorization, request_options=request_options
        )
        return _response.data
