# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.retailer_credentials_list_response import RetailerCredentialsListResponse
from ..types.retailer_credentials_response import RetailerCredentialsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawManagedAccountsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_retailer_credentials(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RetailerCredentialsListResponse]:
        """
        List all retailer credentials for the current user.
        If is_global=True (admin only), list global credentials instead.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size (default 50, max 500). Responses include `total` for paging past it.

        offset : typing.Optional[int]
            Number of credentials to skip

        search : typing.Optional[str]
            Partial match on email or retailer

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetailerCredentialsListResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "managed-accounts",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
                "search": search,
            },
            headers={
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetailerCredentialsListResponse,
                    parse_obj_as(
                        type_=RetailerCredentialsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_retailer_credentials(
        self,
        *,
        email: str,
        authorization: typing.Optional[str] = None,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RetailerCredentialsResponse]:
        """
        Create new retailer credentials for the current user.
        If is_global=True (admin only), creates global credentials owned by the system user.

        Parameters
        ----------
        email : str

        authorization : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]
            Retailer name (e.g., 'amazon'). If null, applies as default credentials.

        totp_secret : typing.Optional[str]
            TOTP secret key for 2FA (will be encrypted at rest).

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetailerCredentialsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "managed-accounts",
            method="POST",
            json={
                "email": email,
                "password": password,
                "retailer": retailer,
                "totp_secret": totp_secret,
                "retailer_config": retailer_config,
            },
            headers={
                "content-type": "application/json",
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetailerCredentialsResponse,
                    parse_obj_as(
                        type_=RetailerCredentialsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        email: typing.Optional[str] = OMIT,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RetailerCredentialsResponse]:
        """
        Update retailer credentials for the current user.
        Admins can also update global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        email : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]

        totp_secret : typing.Optional[str]

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetailerCredentialsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"managed-accounts/{encode_path_param(short_id)}",
            method="PUT",
            json={
                "email": email,
                "password": password,
                "retailer": retailer,
                "totp_secret": totp_secret,
                "retailer_config": retailer_config,
            },
            headers={
                "content-type": "application/json",
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetailerCredentialsResponse,
                    parse_obj_as(
                        type_=RetailerCredentialsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[None]:
        """
        Delete retailer credentials for the current user.
        Admins can also delete global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"managed-accounts/{encode_path_param(short_id)}",
            method="DELETE",
            headers={
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawManagedAccountsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_retailer_credentials(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RetailerCredentialsListResponse]:
        """
        List all retailer credentials for the current user.
        If is_global=True (admin only), list global credentials instead.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size (default 50, max 500). Responses include `total` for paging past it.

        offset : typing.Optional[int]
            Number of credentials to skip

        search : typing.Optional[str]
            Partial match on email or retailer

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetailerCredentialsListResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "managed-accounts",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
                "search": search,
            },
            headers={
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetailerCredentialsListResponse,
                    parse_obj_as(
                        type_=RetailerCredentialsListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_retailer_credentials(
        self,
        *,
        email: str,
        authorization: typing.Optional[str] = None,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RetailerCredentialsResponse]:
        """
        Create new retailer credentials for the current user.
        If is_global=True (admin only), creates global credentials owned by the system user.

        Parameters
        ----------
        email : str

        authorization : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]
            Retailer name (e.g., 'amazon'). If null, applies as default credentials.

        totp_secret : typing.Optional[str]
            TOTP secret key for 2FA (will be encrypted at rest).

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetailerCredentialsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "managed-accounts",
            method="POST",
            json={
                "email": email,
                "password": password,
                "retailer": retailer,
                "totp_secret": totp_secret,
                "retailer_config": retailer_config,
            },
            headers={
                "content-type": "application/json",
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetailerCredentialsResponse,
                    parse_obj_as(
                        type_=RetailerCredentialsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        email: typing.Optional[str] = OMIT,
        password: typing.Optional[str] = OMIT,
        retailer: typing.Optional[str] = OMIT,
        totp_secret: typing.Optional[str] = OMIT,
        retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RetailerCredentialsResponse]:
        """
        Update retailer credentials for the current user.
        Admins can also update global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        email : typing.Optional[str]

        password : typing.Optional[str]

        retailer : typing.Optional[str]

        totp_secret : typing.Optional[str]

        retailer_config : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetailerCredentialsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"managed-accounts/{encode_path_param(short_id)}",
            method="PUT",
            json={
                "email": email,
                "password": password,
                "retailer": retailer,
                "totp_secret": totp_secret,
                "retailer_config": retailer_config,
            },
            headers={
                "content-type": "application/json",
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetailerCredentialsResponse,
                    parse_obj_as(
                        type_=RetailerCredentialsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_retailer_credentials(
        self,
        short_id: str,
        *,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[None]:
        """
        Delete retailer credentials for the current user.
        Admins can also delete global credentials.

        Parameters
        ----------
        short_id : str

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"managed-accounts/{encode_path_param(short_id)}",
            method="DELETE",
            headers={
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
