# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_product_details_products_product_id_get_response_variants_item_properties_item import (
    GetProductDetailsProductsProductIdGetResponseVariantsItemPropertiesItem,
)


class GetProductDetailsProductsProductIdGetResponseVariantsItem(UniversalBaseModel):
    variant_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Variant id. Shopify: pass it when ordering to pick this variant.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Shopify only. Variant title, e.g. `Black / Large`.
    """

    sku: typing.Optional[str] = pydantic.Field(default=None)
    """
    Merchant SKU.
    """

    price: typing.Optional[int] = pydantic.Field(default=None)
    """
    Price in cents (minor units of `currency_code` on Etsy).
    """

    currency_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Etsy only. Currency of `price`.
    """

    quantity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Etsy only. Units in stock.
    """

    available: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this variant can be bought.
    """

    properties: typing.Optional[
        typing.List[GetProductDetailsProductsProductIdGetResponseVariantsItemPropertiesItem]
    ] = pydantic.Field(default=None)
    """
    Etsy only. Axis/value pairs that identify this variant.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
