# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetProductOffersProductsProductIdOffersGetResponseOffersItemHandlingDays(UniversalBaseModel):
    """
    Time before the seller ships.
    """

    min: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum handling time in days.
    """

    max: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum handling time in days.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
