# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetProductDetailsProductsProductIdGetResponseAllVariantsItemVariantSpecificsItem(UniversalBaseModel):
    dimension: typing.Optional[str] = pydantic.Field(default=None)
    """
    Variant axis, e.g. `Color` or `Size`.
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    Value on that axis, e.g. `Black` or `Large`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
