# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_product_offers_products_product_id_offers_get_response_offers_item_condition import (
    GetProductOffersProductsProductIdOffersGetResponseOffersItemCondition,
)
from .get_product_offers_products_product_id_offers_get_response_offers_item_handling_days import (
    GetProductOffersProductsProductIdOffersGetResponseOffersItemHandlingDays,
)
from .get_product_offers_products_product_id_offers_get_response_offers_item_seller import (
    GetProductOffersProductsProductIdOffersGetResponseOffersItemSeller,
)
from .get_product_offers_products_product_id_offers_get_response_offers_item_shipping_options_item import (
    GetProductOffersProductsProductIdOffersGetResponseOffersItemShippingOptionsItem,
)


class GetProductOffersProductsProductIdOffersGetResponseOffersItem(UniversalBaseModel):
    offer_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Retailer's identifier for this offer. Amazon: the offer listing id.
    """

    price: typing.Optional[int] = pydantic.Field(default=None)
    """
    Item price in cents, excluding shipping.
    """

    condition: typing.Optional[GetProductOffersProductsProductIdOffersGetResponseOffersItemCondition] = pydantic.Field(
        default=None
    )
    """
    Item condition.
    """

    available: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the offer can currently be bought.
    """

    seller: typing.Optional[GetProductOffersProductsProductIdOffersGetResponseOffersItemSeller] = pydantic.Field(
        default=None
    )
    """
    Who is selling this offer.
    """

    marketplace_fulfilled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Shipped by the retailer rather than the seller. Amazon: the offer ships with Prime.
    """

    prime_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Amazon only. Only Prime members can buy this offer.
    """

    international: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Ships from outside the United States.
    """

    addon: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Amazon only. Add-on item that can only be bought alongside other items.
    """

    minimum_quantity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum order quantity, when the seller imposes one.
    """

    handling_days: typing.Optional[GetProductOffersProductsProductIdOffersGetResponseOffersItemHandlingDays] = (
        pydantic.Field(default=None)
    )
    """
    Time before the seller ships.
    """

    shipping_options: typing.Optional[
        typing.List[GetProductOffersProductsProductIdOffersGetResponseOffersItemShippingOptionsItem]
    ] = pydantic.Field(default=None)
    """
    Shipping methods offered by this seller.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
