# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_product_details_products_product_id_get_request_retailer import (
        GetProductDetailsProductsProductIdGetRequestRetailer,
    )
    from .get_product_offers_products_product_id_offers_get_request_retailer import (
        GetProductOffersProductsProductIdOffersGetRequestRetailer,
    )
    from .search_products_products_search_get_request_retailer import SearchProductsProductsSearchGetRequestRetailer
_dynamic_imports: typing.Dict[str, str] = {
    "GetProductDetailsProductsProductIdGetRequestRetailer": ".get_product_details_products_product_id_get_request_retailer",
    "GetProductOffersProductsProductIdOffersGetRequestRetailer": ".get_product_offers_products_product_id_offers_get_request_retailer",
    "SearchProductsProductsSearchGetRequestRetailer": ".search_products_products_search_get_request_retailer",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetProductDetailsProductsProductIdGetRequestRetailer",
    "GetProductOffersProductsProductIdOffersGetRequestRetailer",
    "SearchProductsProductsSearchGetRequestRetailer",
]
