# This file was auto-generated by Fern from our API Definition.

import typing

GetProductOffersProductsProductIdOffersGetRequestRetailer = typing.Union[
    typing.Literal["amazon", "walmart"], typing.Any
]
