# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.payment_required_error import PaymentRequiredError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.address import Address
from ..types.customer_notifications import CustomerNotifications
from ..types.order_payment import OrderPayment
from ..types.order_product import OrderProduct
from ..types.order_response import OrderResponse
from ..types.product_search_response import ProductSearchResponse
from ..types.search_response import SearchResponse
from .types.agent_product_details_request_retailer import AgentProductDetailsRequestRetailer
from .types.agent_product_details_response import AgentProductDetailsResponse
from .types.agent_product_offers_request_retailer import AgentProductOffersRequestRetailer
from .types.agent_product_offers_response import AgentProductOffersResponse
from .types.agent_product_search_request_retailer import AgentProductSearchRequestRetailer
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAgentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_mpp_order(
        self,
        *,
        products: typing.Sequence[OrderProduct],
        shipping_address: Address,
        max_price: int,
        method: typing.Optional[str] = None,
        authorization: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = OMIT,
        retailer_credentials_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        po_number: typing.Optional[str] = OMIT,
        handling_days_max: typing.Optional[int] = OMIT,
        is_gift: typing.Optional[bool] = OMIT,
        gift_message: typing.Optional[str] = OMIT,
        payment: typing.Optional[OrderPayment] = OMIT,
        customer_notifications: typing.Optional[CustomerNotifications] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrderResponse]:
        """
        Place an order via the Machine Payments Protocol (MPP).

        No Zinc account required. Payment is made upfront via MPP.
        Supports multiple payment methods (e.g. Tempo, Stripe).
        If no valid payment credential is provided, returns HTTP 402
        with payment challenges for all configured methods.

        Payment is the gate, but only for a genuine discovery probe: a bodyless
        POST (from a registry like mppscan) is parsed leniently and reaches the 402
        challenge instead of a 422. A *present-but-invalid* body, by contrast —
        including malformed JSON and non-object JSON — is a real order attempt
        and is rejected with a 422 up front, before any payment
        challenge is issued or honored. Otherwise an agent could settle an on-chain
        payment against the challenge and then be rejected on the retry, with no way
        to refund the settlement (the MPP layer cannot verify or reverse a payment
        whose retry body no longer matches the challenge).

        Parameters
        ----------
        products : typing.Sequence[OrderProduct]

        shipping_address : Address

        max_price : int
            Maximum price (in cents) allowed for an order before it is finalized.

        method : typing.Optional[str]
            Restrict the 402 to a single payment method (e.g. 'stripe', 'tempo', or 'x402'). Omit to advertise every configured method. Use this when your client can satisfy only one rail — it avoids returning multiple WWW-Authenticate challenges, which many HTTP clients mishandle.

        authorization : typing.Optional[str]

        idempotency_key : typing.Optional[str]
            Optional idempotency key to prevent duplicate orders. If not provided, one will be generated.

        retailer_credentials_id : typing.Optional[str]
            Optional short ID (e.g., 'zn_acct_XXXXXXXX') of specific retailer credentials to use for this order. If not provided, credentials will be selected automatically.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Optional metadata to attach to the order. Can contain arbitrary key-value pairs.

        po_number : typing.Optional[str]
            Optional purchase order number for the order.

        handling_days_max : typing.Optional[int]
            Optional ceiling on a seller's shipping and handling days. Omit or send null for no limit.

        is_gift : typing.Optional[bool]
            Mark the order as a gift, suppressing prices on the packing slip. If the retailer's checkout offers no free gift option, the order FAILS with `gift_option_unavailable` rather than being placed as a normal order — a gift that arrives with prices visible to the recipient is treated as worse than no order.

        gift_message : typing.Optional[str]
            Optional note for the recipient, entered into the retailer's gift-message field at checkout. Requires `is_gift` to be true. Max 240 characters. Delivered where the retailer's checkout offers a gift message; the order is still placed without it where one isn't available.

        payment : typing.Optional[OrderPayment]
            Optional payment block. Omit for prepaid-wallet billing (default).

        customer_notifications : typing.Optional[CustomerNotifications]
            Opt in to emailing the end customer order updates (and unlock the public tracking page for this order). Adds a per-order surcharge. Omit for no customer notifications (default).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrderResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent/orders",
            method="POST",
            params={
                "method": method,
            },
            json={
                "products": convert_and_respect_annotation_metadata(
                    object_=products, annotation=typing.Sequence[OrderProduct], direction="write"
                ),
                "shipping_address": convert_and_respect_annotation_metadata(
                    object_=shipping_address, annotation=Address, direction="write"
                ),
                "max_price": max_price,
                "idempotency_key": idempotency_key,
                "retailer_credentials_id": retailer_credentials_id,
                "metadata": metadata,
                "po_number": po_number,
                "handling_days_max": handling_days_max,
                "is_gift": is_gift,
                "gift_message": gift_message,
                "payment": convert_and_respect_annotation_metadata(
                    object_=payment, annotation=typing.Optional[OrderPayment], direction="write"
                ),
                "customer_notifications": convert_and_respect_annotation_metadata(
                    object_=customer_notifications, annotation=typing.Optional[CustomerNotifications], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderResponse,
                    parse_obj_as(
                        type_=OrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search(
        self, *, q: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SearchResponse]:
        """
        **Beta** — response shape may change. Cross-retailer product search for agents. Returns orderable listings whose
        `url` can be passed straight to POST /agent/orders.

        Parameters
        ----------
        q : str
            Search term

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent/search",
            method="POST",
            params={
                "q": q,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchResponse,
                    parse_obj_as(
                        type_=SearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def product_search(
        self,
        *,
        query: str,
        retailer: AgentProductSearchRequestRetailer,
        page: typing.Optional[int] = None,
        free_shipping: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ProductSearchResponse]:
        """
        Per-retailer product search for agents (amazon | walmart).

        Parameters
        ----------
        query : str
            Search term

        retailer : AgentProductSearchRequestRetailer
            Retailer: amazon or walmart

        page : typing.Optional[int]
            Page number for pagination

        free_shipping : typing.Optional[bool]
            Only return items that ship for free (Walmart: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so Amazon results are returned unfiltered. Applied per-page after pagination; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ProductSearchResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent/products/search",
            method="POST",
            params={
                "query": query,
                "retailer": retailer,
                "page": page,
                "free_shipping": free_shipping,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ProductSearchResponse,
                    parse_obj_as(
                        type_=ProductSearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def product_offers(
        self,
        *,
        product_id: str,
        retailer: AgentProductOffersRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentProductOffersResponse]:
        """
        Offers/pricing for a specific product on a retailer.

        Parameters
        ----------
        product_id : str
            Product identifier (e.g. ASIN)

        retailer : AgentProductOffersRequestRetailer
            Retailer: amazon or walmart

        max_age : typing.Optional[int]
            Max response age in seconds

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentProductOffersResponse]
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent/products/offers",
            method="POST",
            params={
                "product_id": product_id,
                "retailer": retailer,
                "max_age": max_age,
                "newer_than": newer_than,
                "async": async_,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentProductOffersResponse,
                    parse_obj_as(
                        type_=AgentProductOffersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def product_details(
        self,
        *,
        product_id: str,
        retailer: AgentProductDetailsRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[AgentProductDetailsResponse]:
        """
        Full product details for a specific product on a retailer.

        Parameters
        ----------
        product_id : str
            Product identifier (e.g. ASIN)

        retailer : AgentProductDetailsRequestRetailer
            Retailer: amazon or walmart

        max_age : typing.Optional[int]
            Max response age in seconds

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[AgentProductDetailsResponse]
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).
        """
        _response = self._client_wrapper.httpx_client.request(
            "agent/products/details",
            method="POST",
            params={
                "product_id": product_id,
                "retailer": retailer,
                "max_age": max_age,
                "newer_than": newer_than,
                "async": async_,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentProductDetailsResponse,
                    parse_obj_as(
                        type_=AgentProductDetailsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAgentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_mpp_order(
        self,
        *,
        products: typing.Sequence[OrderProduct],
        shipping_address: Address,
        max_price: int,
        method: typing.Optional[str] = None,
        authorization: typing.Optional[str] = None,
        idempotency_key: typing.Optional[str] = OMIT,
        retailer_credentials_id: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        po_number: typing.Optional[str] = OMIT,
        handling_days_max: typing.Optional[int] = OMIT,
        is_gift: typing.Optional[bool] = OMIT,
        gift_message: typing.Optional[str] = OMIT,
        payment: typing.Optional[OrderPayment] = OMIT,
        customer_notifications: typing.Optional[CustomerNotifications] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrderResponse]:
        """
        Place an order via the Machine Payments Protocol (MPP).

        No Zinc account required. Payment is made upfront via MPP.
        Supports multiple payment methods (e.g. Tempo, Stripe).
        If no valid payment credential is provided, returns HTTP 402
        with payment challenges for all configured methods.

        Payment is the gate, but only for a genuine discovery probe: a bodyless
        POST (from a registry like mppscan) is parsed leniently and reaches the 402
        challenge instead of a 422. A *present-but-invalid* body, by contrast —
        including malformed JSON and non-object JSON — is a real order attempt
        and is rejected with a 422 up front, before any payment
        challenge is issued or honored. Otherwise an agent could settle an on-chain
        payment against the challenge and then be rejected on the retry, with no way
        to refund the settlement (the MPP layer cannot verify or reverse a payment
        whose retry body no longer matches the challenge).

        Parameters
        ----------
        products : typing.Sequence[OrderProduct]

        shipping_address : Address

        max_price : int
            Maximum price (in cents) allowed for an order before it is finalized.

        method : typing.Optional[str]
            Restrict the 402 to a single payment method (e.g. 'stripe', 'tempo', or 'x402'). Omit to advertise every configured method. Use this when your client can satisfy only one rail — it avoids returning multiple WWW-Authenticate challenges, which many HTTP clients mishandle.

        authorization : typing.Optional[str]

        idempotency_key : typing.Optional[str]
            Optional idempotency key to prevent duplicate orders. If not provided, one will be generated.

        retailer_credentials_id : typing.Optional[str]
            Optional short ID (e.g., 'zn_acct_XXXXXXXX') of specific retailer credentials to use for this order. If not provided, credentials will be selected automatically.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Optional metadata to attach to the order. Can contain arbitrary key-value pairs.

        po_number : typing.Optional[str]
            Optional purchase order number for the order.

        handling_days_max : typing.Optional[int]
            Optional ceiling on a seller's shipping and handling days. Omit or send null for no limit.

        is_gift : typing.Optional[bool]
            Mark the order as a gift, suppressing prices on the packing slip. If the retailer's checkout offers no free gift option, the order FAILS with `gift_option_unavailable` rather than being placed as a normal order — a gift that arrives with prices visible to the recipient is treated as worse than no order.

        gift_message : typing.Optional[str]
            Optional note for the recipient, entered into the retailer's gift-message field at checkout. Requires `is_gift` to be true. Max 240 characters. Delivered where the retailer's checkout offers a gift message; the order is still placed without it where one isn't available.

        payment : typing.Optional[OrderPayment]
            Optional payment block. Omit for prepaid-wallet billing (default).

        customer_notifications : typing.Optional[CustomerNotifications]
            Opt in to emailing the end customer order updates (and unlock the public tracking page for this order). Adds a per-order surcharge. Omit for no customer notifications (default).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrderResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent/orders",
            method="POST",
            params={
                "method": method,
            },
            json={
                "products": convert_and_respect_annotation_metadata(
                    object_=products, annotation=typing.Sequence[OrderProduct], direction="write"
                ),
                "shipping_address": convert_and_respect_annotation_metadata(
                    object_=shipping_address, annotation=Address, direction="write"
                ),
                "max_price": max_price,
                "idempotency_key": idempotency_key,
                "retailer_credentials_id": retailer_credentials_id,
                "metadata": metadata,
                "po_number": po_number,
                "handling_days_max": handling_days_max,
                "is_gift": is_gift,
                "gift_message": gift_message,
                "payment": convert_and_respect_annotation_metadata(
                    object_=payment, annotation=typing.Optional[OrderPayment], direction="write"
                ),
                "customer_notifications": convert_and_respect_annotation_metadata(
                    object_=customer_notifications, annotation=typing.Optional[CustomerNotifications], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
                "authorization": str(authorization) if authorization is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrderResponse,
                    parse_obj_as(
                        type_=OrderResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search(
        self, *, q: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SearchResponse]:
        """
        **Beta** — response shape may change. Cross-retailer product search for agents. Returns orderable listings whose
        `url` can be passed straight to POST /agent/orders.

        Parameters
        ----------
        q : str
            Search term

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent/search",
            method="POST",
            params={
                "q": q,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchResponse,
                    parse_obj_as(
                        type_=SearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def product_search(
        self,
        *,
        query: str,
        retailer: AgentProductSearchRequestRetailer,
        page: typing.Optional[int] = None,
        free_shipping: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ProductSearchResponse]:
        """
        Per-retailer product search for agents (amazon | walmart).

        Parameters
        ----------
        query : str
            Search term

        retailer : AgentProductSearchRequestRetailer
            Retailer: amazon or walmart

        page : typing.Optional[int]
            Page number for pagination

        free_shipping : typing.Optional[bool]
            Only return items that ship for free (Walmart: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so Amazon results are returned unfiltered. Applied per-page after pagination; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ProductSearchResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent/products/search",
            method="POST",
            params={
                "query": query,
                "retailer": retailer,
                "page": page,
                "free_shipping": free_shipping,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ProductSearchResponse,
                    parse_obj_as(
                        type_=ProductSearchResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def product_offers(
        self,
        *,
        product_id: str,
        retailer: AgentProductOffersRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentProductOffersResponse]:
        """
        Offers/pricing for a specific product on a retailer.

        Parameters
        ----------
        product_id : str
            Product identifier (e.g. ASIN)

        retailer : AgentProductOffersRequestRetailer
            Retailer: amazon or walmart

        max_age : typing.Optional[int]
            Max response age in seconds

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentProductOffersResponse]
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent/products/offers",
            method="POST",
            params={
                "product_id": product_id,
                "retailer": retailer,
                "max_age": max_age,
                "newer_than": newer_than,
                "async": async_,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentProductOffersResponse,
                    parse_obj_as(
                        type_=AgentProductOffersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def product_details(
        self,
        *,
        product_id: str,
        retailer: AgentProductDetailsRequestRetailer,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[AgentProductDetailsResponse]:
        """
        Full product details for a specific product on a retailer.

        Parameters
        ----------
        product_id : str
            Product identifier (e.g. ASIN)

        retailer : AgentProductDetailsRequestRetailer
            Retailer: amazon or walmart

        max_age : typing.Optional[int]
            Max response age in seconds

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[AgentProductDetailsResponse]
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).
        """
        _response = await self._client_wrapper.httpx_client.request(
            "agent/products/details",
            method="POST",
            params={
                "product_id": product_id,
                "retailer": retailer,
                "max_age": max_age,
                "newer_than": newer_than,
                "async": async_,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    AgentProductDetailsResponse,
                    parse_obj_as(
                        type_=AgentProductDetailsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 402:
                raise PaymentRequiredError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
