# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.public_retailer_list_response import PublicRetailerListResponse
from .raw_client import AsyncRawRetailersClient, RawRetailersClient


class RetailersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRetailersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRetailersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRetailersClient
        """
        return self._raw_client

    def list_retailers(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        name: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicRetailerListResponse:
        """
        List the retailers Zinc supports — the public "what do you support?" catalog.

        No authentication required. One flat object per retailer brand: identifier,
        domain, countries shipped to, and the free-shipping policy. International
        marketplaces (e.g. amazon.com / amazon.de) are grouped under one brand with
        the country listed in `supported_countries`. Optionally filter by name.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of retailers to return

        offset : typing.Optional[int]
            Number of retailers to skip

        name : typing.Optional[str]
            Filter by name (case-insensitive partial match)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicRetailerListResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.retailers.list_retailers()
        """
        _response = self._raw_client.list_retailers(
            limit=limit, offset=offset, name=name, request_options=request_options
        )
        return _response.data


class AsyncRetailersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRetailersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRetailersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRetailersClient
        """
        return self._raw_client

    async def list_retailers(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        name: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PublicRetailerListResponse:
        """
        List the retailers Zinc supports — the public "what do you support?" catalog.

        No authentication required. One flat object per retailer brand: identifier,
        domain, countries shipped to, and the free-shipping policy. International
        marketplaces (e.g. amazon.com / amazon.de) are grouped under one brand with
        the country listed in `supported_countries`. Optionally filter by name.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of retailers to return

        offset : typing.Optional[int]
            Number of retailers to skip

        name : typing.Optional[str]
            Filter by name (case-insensitive partial match)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PublicRetailerListResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.retailers.list_retailers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_retailers(
            limit=limit, offset=offset, name=name, request_options=request_options
        )
        return _response.data
