# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent_product_details_request_retailer import AgentProductDetailsRequestRetailer
    from .agent_product_details_response import AgentProductDetailsResponse
    from .agent_product_details_response_status import AgentProductDetailsResponseStatus
    from .agent_product_offers_request_retailer import AgentProductOffersRequestRetailer
    from .agent_product_offers_response import AgentProductOffersResponse
    from .agent_product_offers_response_status import AgentProductOffersResponseStatus
    from .agent_product_search_request_retailer import AgentProductSearchRequestRetailer
_dynamic_imports: typing.Dict[str, str] = {
    "AgentProductDetailsRequestRetailer": ".agent_product_details_request_retailer",
    "AgentProductDetailsResponse": ".agent_product_details_response",
    "AgentProductDetailsResponseStatus": ".agent_product_details_response_status",
    "AgentProductOffersRequestRetailer": ".agent_product_offers_request_retailer",
    "AgentProductOffersResponse": ".agent_product_offers_response",
    "AgentProductOffersResponseStatus": ".agent_product_offers_response_status",
    "AgentProductSearchRequestRetailer": ".agent_product_search_request_retailer",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgentProductDetailsRequestRetailer",
    "AgentProductDetailsResponse",
    "AgentProductDetailsResponseStatus",
    "AgentProductOffersRequestRetailer",
    "AgentProductOffersResponse",
    "AgentProductOffersResponseStatus",
    "AgentProductSearchRequestRetailer",
]
