# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentProductDetailsResponseOffersItem(UniversalBaseModel):
    condition: typing.Optional[str] = pydantic.Field(default=None)
    """
    Best Buy's own label: `New`, `Open-Box Excellent`, …
    """

    price: typing.Optional[int] = pydantic.Field(default=None)
    """
    Price in cents for this condition.
    """

    availability: typing.Optional[str] = pydantic.Field(default=None)
    """
    `InStock`, `OutOfStock`, `PreOrder`, …
    """

    new: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this is the new-condition offer.
    """

    seller: typing.Optional[str] = pydantic.Field(default=None)
    """
    Seller name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
