# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_product_offers_response_offers_item_shipping_options_item_delivery_days import (
    AgentProductOffersResponseOffersItemShippingOptionsItemDeliveryDays,
)


class AgentProductOffersResponseOffersItemShippingOptionsItem(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Shipping speed, e.g. `standard`, `one-day`.
    """

    price: typing.Optional[int] = pydantic.Field(default=None)
    """
    Shipping price in cents.
    """

    delivery_days: typing.Optional[AgentProductOffersResponseOffersItemShippingOptionsItemDeliveryDays] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
