# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_product_details_response_package_dimensions_size import AgentProductDetailsResponsePackageDimensionsSize
from .agent_product_details_response_package_dimensions_weight import AgentProductDetailsResponsePackageDimensionsWeight


class AgentProductDetailsResponsePackageDimensions(UniversalBaseModel):
    """
    Amazon only. Shipping weight and package size.
    """

    weight: typing.Optional[AgentProductDetailsResponsePackageDimensionsWeight] = None
    size: typing.Optional[AgentProductDetailsResponsePackageDimensionsSize] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
