# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bulk_row_validation import BulkRowValidation


class BulkValidateResponse(UniversalBaseModel):
    """
    Dry-run summary returned before any orders are placed.
    """

    filename: typing.Optional[str] = None
    total_rows: int
    valid_rows: int
    invalid_rows: int
    estimated_total_cents: int
    wallet_balance_cents: int
    sufficient_funds: bool
    rows: typing.Optional[typing.List[BulkRowValidation]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
