# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .components_db import ComponentsDb
from .components_ordering import ComponentsOrdering
from .components_queue import ComponentsQueue


class Components(UniversalBaseModel):
    db: ComponentsDb
    queue: ComponentsQueue
    ordering: ComponentsOrdering

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
