# This file was auto-generated by Fern from our API Definition.

import typing

ErrorCode = typing.Union[
    typing.Literal[
        "unauthorized",
        "forbidden",
        "invalid_token",
        "token_expired",
        "not_found",
        "already_exists",
        "validation_error",
        "insufficient_funds",
        "payment_failed",
        "payment_method_required",
        "invalid_payment_method",
        "invalid_shipping_address",
        "url_unreachable",
        "non_us_retailer",
        "unsupported_retailer",
        "unsupported_country",
        "retailer_country_not_supported",
        "guest_checkout_not_supported",
        "invalid_variant",
        "out_of_stock",
        "shipping_unavailable",
        "order_not_cancellable",
        "return_not_allowed",
        "external_service_error",
        "stripe_error",
        "stytch_error",
        "internal_error",
        "bad_request",
        "rate_limit_exceeded",
        "service_unavailable",
    ],
    typing.Any,
]
