# This file was auto-generated by Fern from our API Definition.

import typing

OrderMilestoneType = typing.Union[
    typing.Literal[
        "order_created",
        "order_placed",
        "tracking_acquired",
        "shipped",
        "delivered",
        "undeliverable",
        "order_failed",
        "cancelled",
    ],
    typing.Any,
]
