# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_connect_info import OrderConnectInfo
from .order_item_response import OrderItemResponse
from .order_job_result import OrderJobResult
from .order_status import OrderStatus
from .return_request_summary import ReturnRequestSummary
from .tracking_number_response import TrackingNumberResponse


class OrderResponse(UniversalBaseModel):
    """
    Response model for order data.
    """

    id: str
    status: OrderStatus
    max_price: int
    attempts: int
    items: typing.List[OrderItemResponse]
    shipping_address: typing.Dict[str, typing.Any]
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    po_number: typing.Optional[str] = None
    handling_days_max: typing.Optional[int] = None
    is_gift: typing.Optional[bool] = None
    retailer_credentials_id: typing.Optional[str] = None
    retailer_credentials_uuid: typing.Optional[str] = None
    job_result: typing.Optional[OrderJobResult] = pydantic.Field(default=None)
    """
    Fulfillment result and price breakdown for a completed or failed order; null while processing.
    """

    tracking_numbers: typing.Optional[typing.List[TrackingNumberResponse]] = None
    created_by: typing.Optional[str] = None
    user_id: typing.Optional[int] = None
    returns: typing.Optional[typing.List[ReturnRequestSummary]] = None
    connect: typing.Optional[OrderConnectInfo] = pydantic.Field(default=None)
    """
    Stripe Connect charge details when this order was paid via Connect; null for prepaid-wallet orders.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
