# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_item_status import OrderItemStatus
from .product_condition import ProductCondition
from .product_variant import ProductVariant


class OrderItemResponse(UniversalBaseModel):
    """
    Response model for order item data.

    Field names mirror the OrderItem model, so callers build it with
    ``OrderItemResponse.model_validate(item)`` rather than enumerating fields.
    """

    id: str
    url: str
    quantity: int
    variant: typing.Optional[typing.List[ProductVariant]] = None
    condition_in: typing.Optional[typing.List[ProductCondition]] = None
    condition_not_in: typing.Optional[typing.List[ProductCondition]] = None
    status: OrderItemStatus
    cancellation_reason: typing.Optional[str] = None
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
