# This file was auto-generated by Fern from our API Definition.

import typing

ProductCondition = typing.Union[
    typing.Literal["New", "Refurbished", "UsedLikeNew", "UsedVeryGood", "UsedGood", "UsedAcceptable"], typing.Any
]
