# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .product_search_result import ProductSearchResult


class ProductSearchResponse(UniversalBaseModel):
    """
    Response from the product search endpoint.
    """

    status: str
    results: typing.Optional[typing.List[ProductSearchResult]] = None
    next_page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Only set on free_shipping searches: the page to request to keep paging. An empty `results` with a non-null next_page is NOT the end of results — request next_page to continue. None means results are exhausted (or the search was unfiltered).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
