# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tracking_checkpoint_response import TrackingCheckpointResponse
from .tracking_status import TrackingStatus


class PublicTrackingShipment(UniversalBaseModel):
    """
    One package (tracking number) on the public tracking page.

    Intentionally minimal: carrier + tracking number (the page links to the
    carrier's own tracking site), status, ETA, and the scan history. The
    17track URL and Zinc alias are deliberately NOT exposed here.
    """

    carrier: str
    tracking_number: str
    status: typing.Optional[TrackingStatus] = None
    estimated_delivery_date: typing.Optional[dt.date] = None
    checkpoints: typing.Optional[typing.List[TrackingCheckpointResponse]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
