# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RetailerCredentialsResponse(UniversalBaseModel):
    """
    Response model for retailer credentials.
    """

    id: str
    short_id: str
    email: str
    retailer: typing.Optional[str] = None
    has_totp: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether TOTP 2FA is configured for this account.
    """

    has_forwarding: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether email forwarding has been verified for this account.
    """

    is_paused: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this credential is paused (jobs will not be picked up).
    """

    locked_by_job_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The job ID currently using this credential, if any.
    """

    cooldown_minutes: typing.Optional[int] = pydantic.Field(default=None)
    """
    Minimum minutes between uses. None = no cooldown.
    """

    last_used_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this credential was last released after a job completed.
    """

    retailer_config: typing.Optional[typing.Dict[str, typing.Any]] = None
    forwarding_email: str = pydantic.Field()
    """
    Email address to forward retailer emails to for verification and 2FA code extraction.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
