# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retailer_credentials_response import RetailerCredentialsResponse


class RetailerCredentialsListResponse(UniversalBaseModel):
    """
    Response model for list of retailer credentials.
    """

    credentials: typing.List[RetailerCredentialsResponse]
    total: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
