# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.product_search_response import ProductSearchResponse
from .raw_client import AsyncRawProductsClient, RawProductsClient
from .types.get_product_details_products_product_id_get_response import GetProductDetailsProductsProductIdGetResponse
from .types.get_product_offers_products_product_id_offers_get_response import (
    GetProductOffersProductsProductIdOffersGetResponse,
)


class ProductsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProductsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProductsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProductsClient
        """
        return self._raw_client

    def search_products(
        self,
        *,
        query: str,
        retailer: str,
        page: typing.Optional[int] = None,
        free_shipping: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductSearchResponse:
        """
        Search for products on a retailer.

        **Best Buy returns a partial page.** Best Buy server-renders only about 4 of
        the ~24 products on a search page and loads the rest in the browser, so each
        page yields roughly 4 results rather than a full page. Ranking, pricing and
        availability are Best Buy's own; there are simply fewer items per page. Page
        through with `next_page` to collect more — `next_page` reflects whether Best
        Buy has further results, not how many came back in this response.

        **Shopify stores are their own retailer**: pass the store's domain as
        `retailer` (e.g. `retailer=yetch.studio`; any Shopify-powered storefront
        works). Results are the store's own top matches (~10) and there is no
        pagination, so `next_page` is always null and `page` must be omitted or 1.
        `product_id` is the store-scoped product handle to pass to the details
        endpoint with the same `retailer`.

        **Etsy search covers US shops, priced in USD.** Etsy sellers price in their
        own currency and a single page routinely mixes several, which makes `price`
        incomparable across a result set — so search is narrowed to US-located
        shops and any remaining non-USD listing is dropped. `currency_code` is set
        on every result and is always `USD` here, and prices are never converted,
        so the number is what the seller charges. Because the currency check runs
        after Etsy paginates, **a page can come back short while more results still
        exist** — page on with `next_page`. (Details is neither narrowed nor
        filtered: it returns any listing, in its own currency.)

        Etsy results carry no `stars`/`num_reviews` — Etsy publishes a rating for
        the *shop*, not the listing, and reporting a seller's rating as the
        product's would be misleading; `brand` carries the shop name, and the
        details endpoint reports the shop's rating explicitly. `product_id` is the
        numeric listing id.

        Parameters
        ----------
        query : str
            Search term

        retailer : str
            Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio)

        page : typing.Optional[int]
            Page number for pagination

        free_shipping : typing.Optional[bool]
            Only return items that ship for free (Walmart and Best Buy: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so filtering on it would drop valid items — Amazon results are returned unfiltered. Filtering happens after pagination, so per-page counts vary; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results. Rejected for Shopify stores: their search data carries no shipping information, so the filter cannot be honored.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductSearchResponse
            Successful Response

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.products.search_products(
            query="query",
            retailer="retailer",
        )
        """
        _response = self._raw_client.search_products(
            query=query,
            retailer=retailer,
            page=page,
            free_shipping=free_shipping,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    def get_product_offers(
        self,
        product_id: str,
        *,
        retailer: str,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetProductOffersProductsProductIdOffersGetResponse:
        """
        Get offers for a product from a retailer.

        Not available for Shopify stores: a storefront lists one seller (itself),
        so per-variant price and availability live on the details endpoint instead.

        Parameters
        ----------
        product_id : str

        retailer : str
            Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio)

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProductOffersProductsProductIdOffersGetResponse
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.products.get_product_offers(
            product_id="product_id",
            retailer="retailer",
        )
        """
        _response = self._raw_client.get_product_offers(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    def get_product_details(
        self,
        product_id: str,
        *,
        retailer: str,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetProductDetailsProductsProductIdGetResponse:
        """
        Get details for a product from a retailer.

        **Best Buy is addressed by `bsin`**, not by the numeric SKU — the bsin is the
        trailing id in a Best Buy product URL (`/product/{slug}/{bsin}`). Search
        results return the SKU as `product_id` and also carry the bsin, so pass the
        bsin here. The response repeats the SKU as `sku` for cross-referencing.

        Unlike `/search`, a Best Buy detail response is complete: detail pages are
        fully server-rendered, so nothing is withheld for client-side loading.

        **Shopify is addressed by (store, handle)**: pass the store's domain as
        `retailer` (e.g. `retailer=yetch.studio`) and the product handle — the slug
        in `/products/{handle}`, returned as `product_id` by search — as the path
        parameter. The response includes per-variant price and availability.
        `async` is not supported for Shopify stores.

        **Etsy is addressed by the numeric listing id** (returned as `product_id` by
        search). `price` is in minor units of `currency_code`, not converted to USD.

        Etsy ratings are the **shop's**, reported as `shop_review_average` /
        `shop_review_count`, and both cover only the **past year** — an established
        shop with no recent sales reports 0, and an unrated shop reports a null
        average rather than 0.0 stars. `stars` and `num_reviews` are deliberately
        not set: they mean a product's rating everywhere else in this API, and a
        seller's rating is a different claim.

        `listing_type` is `physical`, `download` or `both` — a download has nothing
        to ship. `available` accounts for the shop being on vacation as well as
        stock, so it can be false on an in-stock active listing; `shop_is_vacation`
        says which it was. `variants` is populated only when Etsy exposes a
        listing's inventory matrix — check `has_variations` to tell "no variants"
        from "variants not visible". `taxonomy_id` is Etsy's raw category id; there
        is no category name yet. `async` is not supported for Etsy.

        Parameters
        ----------
        product_id : str

        retailer : str
            Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio)

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProductDetailsProductsProductIdGetResponse
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).

        Examples
        --------
        from zinc import ZincClient

        client = ZincClient(
            api_key="YOUR_API_KEY",
        )
        client.products.get_product_details(
            product_id="product_id",
            retailer="retailer",
        )
        """
        _response = self._raw_client.get_product_details(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data


class AsyncProductsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProductsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProductsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProductsClient
        """
        return self._raw_client

    async def search_products(
        self,
        *,
        query: str,
        retailer: str,
        page: typing.Optional[int] = None,
        free_shipping: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ProductSearchResponse:
        """
        Search for products on a retailer.

        **Best Buy returns a partial page.** Best Buy server-renders only about 4 of
        the ~24 products on a search page and loads the rest in the browser, so each
        page yields roughly 4 results rather than a full page. Ranking, pricing and
        availability are Best Buy's own; there are simply fewer items per page. Page
        through with `next_page` to collect more — `next_page` reflects whether Best
        Buy has further results, not how many came back in this response.

        **Shopify stores are their own retailer**: pass the store's domain as
        `retailer` (e.g. `retailer=yetch.studio`; any Shopify-powered storefront
        works). Results are the store's own top matches (~10) and there is no
        pagination, so `next_page` is always null and `page` must be omitted or 1.
        `product_id` is the store-scoped product handle to pass to the details
        endpoint with the same `retailer`.

        **Etsy search covers US shops, priced in USD.** Etsy sellers price in their
        own currency and a single page routinely mixes several, which makes `price`
        incomparable across a result set — so search is narrowed to US-located
        shops and any remaining non-USD listing is dropped. `currency_code` is set
        on every result and is always `USD` here, and prices are never converted,
        so the number is what the seller charges. Because the currency check runs
        after Etsy paginates, **a page can come back short while more results still
        exist** — page on with `next_page`. (Details is neither narrowed nor
        filtered: it returns any listing, in its own currency.)

        Etsy results carry no `stars`/`num_reviews` — Etsy publishes a rating for
        the *shop*, not the listing, and reporting a seller's rating as the
        product's would be misleading; `brand` carries the shop name, and the
        details endpoint reports the shop's rating explicitly. `product_id` is the
        numeric listing id.

        Parameters
        ----------
        query : str
            Search term

        retailer : str
            Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio)

        page : typing.Optional[int]
            Page number for pagination

        free_shipping : typing.Optional[bool]
            Only return items that ship for free (Walmart and Best Buy: ship price of 0). Currently a no-op for Amazon: the upstream search data under-reports Prime, so filtering on it would drop valid items — Amazon results are returned unfiltered. Filtering happens after pagination, so per-page counts vary; use `next_page` in the response to keep paging — an empty page with a non-null `next_page` is not the end of results. Rejected for Shopify stores: their search data carries no shipping information, so the filter cannot be honored.

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProductSearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.search_products(
                query="query",
                retailer="retailer",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_products(
            query=query,
            retailer=retailer,
            page=page,
            free_shipping=free_shipping,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    async def get_product_offers(
        self,
        product_id: str,
        *,
        retailer: str,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetProductOffersProductsProductIdOffersGetResponse:
        """
        Get offers for a product from a retailer.

        Not available for Shopify stores: a storefront lists one seller (itself),
        so per-variant price and availability live on the details endpoint instead.

        Parameters
        ----------
        product_id : str

        retailer : str
            Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio)

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProductOffersProductsProductIdOffersGetResponse
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.get_product_offers(
                product_id="product_id",
                retailer="retailer",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_product_offers(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data

    async def get_product_details(
        self,
        product_id: str,
        *,
        retailer: str,
        max_age: typing.Optional[int] = None,
        newer_than: typing.Optional[int] = None,
        async_: typing.Optional[bool] = None,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetProductDetailsProductsProductIdGetResponse:
        """
        Get details for a product from a retailer.

        **Best Buy is addressed by `bsin`**, not by the numeric SKU — the bsin is the
        trailing id in a Best Buy product URL (`/product/{slug}/{bsin}`). Search
        results return the SKU as `product_id` and also carry the bsin, so pass the
        bsin here. The response repeats the SKU as `sku` for cross-referencing.

        Unlike `/search`, a Best Buy detail response is complete: detail pages are
        fully server-rendered, so nothing is withheld for client-side loading.

        **Shopify is addressed by (store, handle)**: pass the store's domain as
        `retailer` (e.g. `retailer=yetch.studio`) and the product handle — the slug
        in `/products/{handle}`, returned as `product_id` by search — as the path
        parameter. The response includes per-variant price and availability.
        `async` is not supported for Shopify stores.

        **Etsy is addressed by the numeric listing id** (returned as `product_id` by
        search). `price` is in minor units of `currency_code`, not converted to USD.

        Etsy ratings are the **shop's**, reported as `shop_review_average` /
        `shop_review_count`, and both cover only the **past year** — an established
        shop with no recent sales reports 0, and an unrated shop reports a null
        average rather than 0.0 stars. `stars` and `num_reviews` are deliberately
        not set: they mean a product's rating everywhere else in this API, and a
        seller's rating is a different claim.

        `listing_type` is `physical`, `download` or `both` — a download has nothing
        to ship. `available` accounts for the shop being on vacation as well as
        stock, so it can be false on an in-stock active listing; `shop_is_vacation`
        says which it was. `variants` is populated only when Etsy exposes a
        listing's inventory matrix — check `has_variations` to tell "no variants"
        from "variants not visible". `taxonomy_id` is Etsy's raw category id; there
        is no category name yet. `async` is not supported for Etsy.

        Parameters
        ----------
        product_id : str

        retailer : str
            Retailer identifier: amazon, walmart, bestbuy, etsy, or a Shopify store's domain (e.g. retailer=yetch.studio)

        max_age : typing.Optional[int]
            Max response age in seconds (mutually exclusive with newer_than)

        newer_than : typing.Optional[int]
            Minimum retrieval timestamp (mutually exclusive with max_age)

        async_ : typing.Optional[bool]
            Return immediately with status=processing

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetProductDetailsProductsProductIdGetResponse
            Retailer payload, passed through unmodified. Fields vary by retailer, so only `status` is guaranteed: `completed` for a resolved response, `processing` when `async=true` and the fetch is still running, `failed` when the retailer returned an error (with `code` and `message`).

        Examples
        --------
        import asyncio

        from zinc import AsyncZincClient

        client = AsyncZincClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.products.get_product_details(
                product_id="product_id",
                retailer="retailer",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_product_details(
            product_id,
            retailer=retailer,
            max_age=max_age,
            newer_than=newer_than,
            async_=async_,
            authorization=authorization,
            request_options=request_options,
        )
        return _response.data
