# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.search_response import SearchResponse
from .raw_client import AsyncRawSearchClient, RawSearchClient


class SearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchClient
        """
        return self._raw_client

    def search(
        self,
        *,
        q: str,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Search for products across retailers; returns orderable zn_sku_ listings.

        Parameters
        ----------
        q : str
            Search term

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            Successful Response

        Examples
        --------
        from zincio import ZincioApi

        client = ZincioApi(
            api_key="YOUR_API_KEY",
        )
        client.search.search(
            q="q",
        )
        """
        _response = self._raw_client.search(q=q, authorization=authorization, request_options=request_options)
        return _response.data


class AsyncSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        q: str,
        authorization: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchResponse:
        """
        Search for products across retailers; returns orderable zn_sku_ listings.

        Parameters
        ----------
        q : str
            Search term

        authorization : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchResponse
            Successful Response

        Examples
        --------
        import asyncio

        from zincio import AsyncZincioApi

        client = AsyncZincioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.search.search(
                q="q",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(q=q, authorization=authorization, request_options=request_options)
        return _response.data
